{
    "items":[
            {
            "label":"ʿAbayh",
            "type":"town",
            "latlng":"33.736923, 35.525698",
            "periodicals":"2",
            "links":
            [ {"url":"./tabdd.html#t1r270","alias":"Al-Ṣafāʾ (1886)"},
                        {"url":"./tabdd.html#t1r270","alias":"Al-Ṣafāʾ (1886)"}]},
                {
            "label":"ʿĀliya",
            "type":"town",
            "latlng":"33.736923, 35.525698",
            "periodicals":"1",
            "links":
            [ {"url":"./tabdd.html#t1r270","alias":"Al-Ṣafāʾ (1886)"}]},
                {
            "label":"Aleppo",
            "type":"city",
            "latlng":"36.20124, 37.16117",
            "periodicals":"7",
            "links":
            [ {"url":"./tabdd.html#t1r44","alias":"Al-Furāt/Furāt (1867)"},
                        {"url":"./tabdd.html#t1r45","alias":"Ghadīr al-Furāt (1867)"},
                        {"url":"./tabdd.html#t1r144","alias":"Al-Iʿtidāl (1879)"},
                        {"url":"./tabdd.html#t1r415","alias":"Al-Marʾa (1893)"},
                        {"url":"./tabdd.html#t1r120","alias":"Al-Shahbā (1877)"},
                        {"url":"./tabdd.html#t1r430","alias":"Al-Shahbāʾ (1893)"},
                        {"url":"./tabdd.html#t1r630","alias":"Al-Shudhūr (1897)"}]},
                {
            "label":"Alexandria",
            "type":"city",
            "latlng":"31.21564, 29.95527",
            "periodicals":"100",
            "links":
            [ {"url":"./tabdd.html#t1r527","alias":"Al-ʿAbbās (1896)"},
                        {"url":"./tabdd.html#t1r161","alias":"Al-ʿAṣr al-Jadīd (1880)"},
                        {"url":"./tabdd.html#t1r714","alias":"Al-ʿUthmānī (1898)"},
                        {"url":"./tabdd.html#t1r479","alias":"Abū Nuwās (1895)"},
                        {"url":"./tabdd.html#t1r638","alias":"Abū Nuwās (1898)"},
                        {"url":"./tabdd.html#t1r528","alias":"Al-Adab (1896)"},
                        {"url":"./tabdd.html#t1r639","alias":"Al-Adab (1898)"},
                        {"url":"./tabdd.html#t1r100","alias":"Al-Ahrām (1876)"},
                        {"url":"./tabdd.html#t1r100","alias":"Al-Ahrām (1876)"},
                        {"url":"./tabdd.html#t1r203","alias":"Al-Aḥwāl (1882)"},
                        {"url":"./tabdd.html#t1r483","alias":"Anīs al-Jalīs (1895)"},
                        {"url":"./tabdd.html#t1r721","alias":"Al-Āmāl (1899)"},
                        {"url":"./tabdd.html#t1r279","alias":"Al-Babghāʾ (1887)"},
                        {"url":"./tabdd.html#t1r788","alias":"Al-Baḥbaḥa (1900)"},
                        {"url":"./tabdd.html#t1r591","alias":"Al-Baṣīr (1897)"},
                        {"url":"./tabdd.html#t1r180","alias":"Al-Burhān (1881)"},
                        {"url":"./tabdd.html#t1r727","alias":"Burhān al-Ḥaqq (1899)"},
                        {"url":"./tabdd.html#t1r650","alias":"Al-Dābba (1898)"},
                        {"url":"./tabdd.html#t1r249","alias":"Al-Fallāh (1885)"},
                        {"url":"./tabdd.html#t1r535","alias":"Faṣl al-Khiṭāb (1896)"},
                        {"url":"./tabdd.html#t1r373","alias":"Al-Fatāt (1892)"},
                        {"url":"./tabdd.html#t1r489","alias":"Fi’l-Ṭarīq (1895)"},
                        {"url":"./tabdd.html#t1r374","alias":"Furṣat al-Awqāt (1892)"},
                        {"url":"./tabdd.html#t1r407","alias":"Furṣat al-Awqāt (1893)"},
                        {"url":"./tabdd.html#t1r293","alias":"Ḥadīqat al-Adab (1888)"},
                        {"url":"./tabdd.html#t1r83","alias":"Ḥadīqat al-Akhbār (1873)"},
                        {"url":"./tabdd.html#t1r323","alias":"Al-Ḥaqīqa (1889)"},
                        {"url":"./tabdd.html#t1r658","alias":"Al-Ḥaqqāniyya (1898)"},
                        {"url":"./tabdd.html#t1r659","alias":"Al-Ḥashshāsh (1898)"},
                        {"url":"./tabdd.html#t1r492","alias":"Ḥaẓẓ al-Ḥayāt (1895)"},
                        {"url":"./tabdd.html#t1r541","alias":"Al-Ḥudūd (1896)"},
                        {"url":"./tabdd.html#t1r543","alias":"Al-Iʿlānāt (1896)"},
                        {"url":"./tabdd.html#t1r207","alias":"Al-Iʿtidāl (1882)"},
                        {"url":"./tabdd.html#t1r740","alias":"Al-Iʿtidāl (1899)"},
                        {"url":"./tabdd.html#t1r446","alias":"Al-Ibtisām (1894)"},
                        {"url":"./tabdd.html#t1r737","alias":"Al-Irshād (1899)"},
                        {"url":"./tabdd.html#t1r129","alias":"Al-Iskandariyya (1878)"},
                        {"url":"./tabdd.html#t1r738","alias":"Al-Iskandariyya (1899)"},
                        {"url":"./tabdd.html#t1r187","alias":"Al-Ittiḥād al-Miṣrī/L’Union Egyptienne (1881)"},
                        {"url":"./tabdd.html#t1r110","alias":"Jarīda Rasmiyya - Journal Officiel pour les Publications Judiciares - Journal Officiel des Tribunaux - Giornale Ufficiale per le Pubblicazioni Giudiziarie (1877)"},
                        {"url":"./tabdd.html#t1r741","alias":"Al-Jāmiʿa (1899)"},
                        {"url":"./tabdd.html#t1r741","alias":"Al-Jāmiʿa (1899)"},
                        {"url":"./tabdd.html#t1r742","alias":"Al-Jāmiʿa al-ʿUthmāniyya (1899)"},
                        {"url":"./tabdd.html#t1r742","alias":"Al-Jāmiʿa al-ʿUthmāniyya (1899)"},
                        {"url":"./tabdd.html#t1r495","alias":"Jūrnāl al-Ṣafā (1895)"},
                        {"url":"./tabdd.html#t1r111","alias":"Al-Kashshāf (1877)"},
                        {"url":"./tabdd.html#t1r743","alias":"Al-Kawkab al-Durrī (1899?)"},
                        {"url":"./tabdd.html#t1r744","alias":"Al-Kawkab al-Miṣrī (1899)"},
                        {"url":"./tabdd.html#t1r745","alias":"Al-Kawkab al-Sārī (1899)"},
                        {"url":"./tabdd.html#t1r86","alias":"Al-Kawkab al-Sharqī (1873)"},
                        {"url":"./tabdd.html#t1r234","alias":"Lisān al-ʿArab (1884)"},
                        {"url":"./tabdd.html#t1r453","alias":"Lisān al-ʿArab (1894)"},
                        {"url":"./tabdd.html#t1r453","alias":"Lisān al-ʿArab (1894)"},
                        {"url":"./tabdd.html#t1r498","alias":"Al-Maghribī al-ʿUthmānī (1895)"},
                        {"url":"./tabdd.html#t1r113","alias":"Al-Maḥrūsa (1877)"},
                        {"url":"./tabdd.html#t1r235","alias":"Al-Maḥrūsa (1884)"},
                        {"url":"./tabdd.html#t1r675","alias":"Majallat al-Nīl (1898)"},
                        {"url":"./tabdd.html#t1r282","alias":"Makārim al-Akhlāq (1887)"},
                        {"url":"./tabdd.html#t1r301","alias":"Al-Manāra (1888)"},
                        {"url":"./tabdd.html#t1r381","alias":"Marqā al-Najāḥ (1892)"},
                        {"url":"./tabdd.html#t1r501","alias":"Al-Marsī (1895)"},
                        {"url":"./tabdd.html#t1r458","alias":"Al-Matḥaf (1894)"},
                        {"url":"./tabdd.html#t1r460","alias":"Al-Minbar (1894)"},
                        {"url":"./tabdd.html#t1r115","alias":"Miṣr (1877)"},
                        {"url":"./tabdd.html#t1r189","alias":"Miṣr (1881)"},
                        {"url":"./tabdd.html#t1r151","alias":"Miṣr al-Fatāt/La Jeune Egypte (1879)"},
                        {"url":"./tabdd.html#t1r463","alias":"Al-Mushīr/ The Counsellor (1894)"},
                        {"url":"./tabdd.html#t1r118","alias":"Nashrat al-Tilighrāf (1877)"},
                        {"url":"./tabdd.html#t1r508","alias":"Al-Nibrās (1895)"},
                        {"url":"./tabdd.html#t1r691","alias":"Al-Nīl (1898)"},
                        {"url":"./tabdd.html#t1r131","alias":"Al-Nīl; Il Nilo, Le Nile (1878)"},
                        {"url":"./tabdd.html#t1r464","alias":"Al-Nūr al-ʿAbbāsī (1894)"},
                        {"url":"./tabdd.html#t1r465","alias":"Al-Qaḍāʾ (1894)"},
                        {"url":"./tabdd.html#t1r509","alias":"Al-Qaḍāʾ (1895)"},
                        {"url":"./tabdd.html#t1r562","alias":"Al-Rafīq (1896)"},
                        {"url":"./tabdd.html#t1r696","alias":"Al-Rajāʾ (1898)"},
                        {"url":"./tabdd.html#t1r697","alias":"Al-Raqīb (1898)"},
                        {"url":"./tabdd.html#t1r214","alias":"Rawḍat al-Iskandariyya (1882)"},
                        {"url":"./tabdd.html#t1r308","alias":"Al-Rāwī (1888)"},
                        {"url":"./tabdd.html#t1r698","alias":"Al-Saʿāda (1898)"},
                        {"url":"./tabdd.html#t1r705","alias":"Al-Salām (1898)"},
                        {"url":"./tabdd.html#t1r226","alias":"Al-Sharq (1883)"},
                        {"url":"./tabdd.html#t1r88","alias":"Shuʿāʿ al-Kawkab al-Sharqī (1873)"},
                        {"url":"./tabdd.html#t1r517","alias":"Al-Sibāq (1895)"},
                        {"url":"./tabdd.html#t1r396","alias":"Al-Surūr (1892)"},
                        {"url":"./tabdd.html#t1r828","alias":"Al-Ṣabāḥ (1900)"},
                        {"url":"./tabdd.html#t1r106","alias":"Ṣadā al-Ahrām (1876)"},
                        {"url":"./tabdd.html#t1r764","alias":"Ṣadā al-Ahrām (1899)"},
                        {"url":"./tabdd.html#t1r702","alias":"Al-Ṣādiq (1898)"},
                        {"url":"./tabdd.html#t1r711","alias":"Al-Taʾrīkh (1898)"},
                        {"url":"./tabdd.html#t1r712","alias":"Al-Taʾrīkh al-Qawmī (1898)"},
                        {"url":"./tabdd.html#t1r633","alias":"Al-Taʾrīkh al-Yawmī (1897)"},
                        {"url":"./tabdd.html#t1r2","alias":"Al-Tanbīh (*1800)"},
                        {"url":"./tabdd.html#t1r198","alias":"Al-Tankīt wa’l-Tabkīt (1881)"},
                        {"url":"./tabdd.html#t1r435","alias":"Al-Thamra (1893)"},
                        {"url":"./tabdd.html#t1r136","alias":"Al-Tijāra (1878)"},
                        {"url":"./tabdd.html#t1r634","alias":"Al-Tijāra (1897)"},
                        {"url":"./tabdd.html#t1r197","alias":"Al-Ṭāʾif (1881)"},
                        {"url":"./tabdd.html#t1r137","alias":"Al-Waqt (li-Jarīdat al-Ahrām) (1878)"},
                        {"url":"./tabdd.html#t1r778","alias":"Al-Ẓuhūr (1899)"}]},
                {
            "label":"Algiers",
            "type":"city",
            "latlng":"36.7525, 3.04197",
            "periodicals":"12",
            "links":
            [ {"url":"./tabdd.html#t1r57","alias":"Adzīrī/L’Israélite Algérien (1870)"},
                        {"url":"./tabdd.html#t1r351","alias":"Bêt Yisra’el / Le Peuple d’Israël (1891)"},
                        {"url":"./tabdd.html#t1r181","alias":"Al-Bustān (1881)"},
                        {"url":"./tabdd.html#t1r794","alias":"Farīḍat al-Ḥajj (1900)"},
                        {"url":"./tabdd.html#t1r408","alias":"Al-Ḥaqq/El-Hack (1893)"},
                        {"url":"./tabdd.html#t1r802","alias":"Al-Jazāʾirī (1900)"},
                        {"url":"./tabdd.html#t1r390","alias":"Le Peuple d’Israël (1892)"},
                        {"url":"./tabdd.html#t1r7","alias":"L’Akhbar (1839?)"},
                        {"url":"./tabdd.html#t1r8","alias":"Al-Mubashshir (1847)"},
                        {"url":"./tabdd.html#t1r192","alias":"Al-Mukhayyir (1881)"},
                        {"url":"./tabdd.html#t1r760","alias":"Al-Nāṣiḥ (Ṭ= Al-Naṣīḥ) (1899)"},
                        {"url":"./tabdd.html#t1r361","alias":"Al-Qamra / La Lune/El-Qamra (1891)"}]},
                {
            "label":"America",
            "type":"continent",
            "latlng":"-14.60485, -57.65625",
            "periodicals":"2",
            "links":
            [ {"url":"./tabdd.html#t1r741","alias":"Al-Jāmiʿa (1899)"},
                        {"url":"./tabdd.html#t1r742","alias":"Al-Jāmiʿa al-ʿUthmāniyya (1899)"}]},
                {
            "label":"Argentina",
            "type":"country",
            "latlng":"-34, -64",
            "periodicals":"5",
            "links":
            [ {"url":"./tabdd.html#t1r769","alias":"al-Ṣubḥ (1899)"},
                        {"url":"./tabdd.html#t1r704","alias":"Al-Sāʿiqa (1898)"},
                        {"url":"./tabdd.html#t1r765","alias":"Ṣadā al-Janūb (1899)"},
                        {"url":"./tabdd.html#t1r835","alias":"Al-Ṣidq (1900)"},
                        {"url":"./tabdd.html#t1r772","alias":"Al-Tamaddun (1899)"}]},
                {
            "label":"Asyūṭ",
            "type":"city",
            "latlng":"27.18096, 31.18368",
            "periodicals":"5",
            "links":
            [ {"url":"./tabdd.html#t1r789","alias":"Būq al-Iṣlāḥ (1900)"},
                        {"url":"./tabdd.html#t1r267","alias":"Al-Nuzha (1886)"},
                        {"url":"./tabdd.html#t1r393","alias":"Al-Rāwī (1892)"},
                        {"url":"./tabdd.html#t1r427","alias":"Al-Rāwī (1893)"},
                        {"url":"./tabdd.html#t1r429","alias":"Riyāḍ al-Tawfīq (1893)"}]},
                {
            "label":"Baʿbdā",
            "type":"town",
            "latlng":"33.833797, 35.544145",
            "periodicals":"5",
            "links":
            [ {"url":"./tabdd.html#t1r46","alias":"Al-Jarīda al-Rasmiyya (1867)"},
                        {"url":"./tabdd.html#t1r359","alias":"Lubnān (1891)"},
                        {"url":"./tabdd.html#t1r616","alias":"Al-Munāẓir (1897)"},
                        {"url":"./tabdd.html#t1r468","alias":"Al-Rawḍa (1894)"},
                        {"url":"./tabdd.html#t1r270","alias":"Al-Ṣafāʾ (1886)"}]},
                {
            "label":"Baghdad",
            "type":"city",
            "latlng":"33.34058, 44.40088",
            "periodicals":"3",
            "links":
            [ {"url":"./tabdd.html#t1r32","alias":"Ha Dôver (1863)"},
                        {"url":"./tabdd.html#t1r4","alias":"Jūrnāl al-ʿIrāq (1816)"},
                        {"url":"./tabdd.html#t1r55","alias":"Al-Zawrāʾ (1869)"}]},
                {
            "label":"Banī Suwayf",
            "type":"city",
            "latlng":"29.07441, 31.09785",
            "periodicals":"1",
            "links":
            [ {"url":"./tabdd.html#t1r734","alias":"Al-Ḥikma (1899)"}]},
                {
            "label":"Basra",
            "type":"city",
            "latlng":"30.53302, 47.79747",
            "periodicals":"1",
            "links":
            [ {"url":"./tabdd.html#t1r488","alias":"Al-Baṣra (1895)"}]},
                {
            "label":"Bayt al-Dīn",
            "type":"city",
            "latlng":"33.7, 35.6",
            "periodicals":"1",
            "links":
            [ {"url":"./tabdd.html#t1r47","alias":"Lubnān (1867)"}]},
                {
            "label":"Beirut",
            "type":"city",
            "latlng":"33.88894, 35.49442",
            "periodicals":"73",
            "links":
            [ {"url":"./tabdd.html#t1r714","alias":"Al-ʿUthmānī (1898)"},
                        {"url":"./tabdd.html#t1r51","alias":"Aʿmāl al-Jamʿiyya al-ʿIlmiyya al-Sūriyya (1868)"},
                        {"url":"./tabdd.html#t1r11","alias":"Aʿmāl al-Jamʿiyya al-Sūriyya (1852)"},
                        {"url":"./tabdd.html#t1r43","alias":"Aʿmāl Sharikat Mār Manṣūr dī Būl (1867)"},
                        {"url":"./tabdd.html#t1r350","alias":"Al-Aḥwāl (1891)"},
                        {"url":"./tabdd.html#t1r31","alias":"Akhbār ʿan Intishār al-Anjīl fi Amākin Mukhtalifa / Al-ʿĀlam (1863)"},
                        {"url":"./tabdd.html#t1r90","alias":"Akhbār Ṭibbiyya (1874)"},
                        {"url":"./tabdd.html#t1r178","alias":"Akhbār Ṭibbiyya (1881)"},
                        {"url":"./tabdd.html#t1r246","alias":"Akhbār Ṭibbiyya (1885)"},
                        {"url":"./tabdd.html#t1r70","alias":"al-Junayna (1871)"},
                        {"url":"./tabdd.html#t1r847","alias":"al-Mabdaʾ al-Ṣaḥīḥ (1899)"},
                        {"url":"./tabdd.html#t1r58","alias":"Al-Bashīr (1870)"},
                        {"url":"./tabdd.html#t1r262","alias":"Bayrūt (1886)"},
                        {"url":"./tabdd.html#t1r290","alias":"Bayrūt (al-Rasmiyya) (1888)"},
                        {"url":"./tabdd.html#t1r125","alias":"Al-Bākūra li-Aʿmāl Jamʿiyyat Musāʿadat al-Marḍā al-Ūrthūdhūksiyya (1878)"},
                        {"url":"./tabdd.html#t1r204","alias":"Dalīl al-Bashīr (1882)"},
                        {"url":"./tabdd.html#t1r292","alias":"Dalīl Bayrūt (li-ʿĀmm) (1888)"},
                        {"url":"./tabdd.html#t1r248","alias":"Dīwān al-Fukāha (1885)"},
                        {"url":"./tabdd.html#t1r317","alias":"Al-Fawāʾid (1889)"},
                        {"url":"./tabdd.html#t1r656","alias":"Ghādat al-Fikar (1898)"},
                        {"url":"./tabdd.html#t1r220","alias":"Al-Hadiyya (1883)"},
                        {"url":"./tabdd.html#t1r796","alias":"Al-Ḥadīqa (1900)"},
                        {"url":"./tabdd.html#t1r21","alias":"Ḥadīqat al-Akhbār (1858)"},
                        {"url":"./tabdd.html#t1r732","alias":"Ḥadīqat al-Maʿārif (1899)"},
                        {"url":"./tabdd.html#t1r601","alias":"Iqdām (c1897)"},
                        {"url":"./tabdd.html#t1r60","alias":"Al-Janna (1870)"},
                        {"url":"./tabdd.html#t1r449","alias":"Al-Jāmiʿa (1894)"},
                        {"url":"./tabdd.html#t1r61","alias":"Al-Jinān (1870)"},
                        {"url":"./tabdd.html#t1r299","alias":"Al-Kanīsa al-Kāthūlīkiyya/L’Eglise Catholique (1888)"},
                        {"url":"./tabdd.html#t1r252","alias":"Kawkab al-ʿIlm (1885)"},
                        {"url":"./tabdd.html#t1r846","alias":"Kawkab al-Sharq (*1894)"},
                        {"url":"./tabdd.html#t1r71","alias":"Kawkab al-Ṣubḥ al-Munīr (1871)"},
                        {"url":"./tabdd.html#t1r806","alias":"Al-Kināna (1900)"},
                        {"url":"./tabdd.html#t1r112","alias":"Lisān al-Ḥāl (1877)"},
                        {"url":"./tabdd.html#t1r750","alias":"Al-Maḥabba (1899)"},
                        {"url":"./tabdd.html#t1r62","alias":"Al-Majmaʿ al-Fātikānī (1870)"},
                        {"url":"./tabdd.html#t1r52","alias":"Majmūʿat al-ʿUlūm (1868)"},
                        {"url":"./tabdd.html#t1r12","alias":"Majmūʿ Fawāyid li-Nakhbat Afāḍil (1853)"},
                        {"url":"./tabdd.html#t1r300","alias":"Al-Maktaba al-Kāthūlīkiyya (1888)"},
                        {"url":"./tabdd.html#t1r677","alias":"Al-Manār (1898)"},
                        {"url":"./tabdd.html#t1r813","alias":"Al-Manār (1900)"},
                        {"url":"./tabdd.html#t1r752","alias":"Al-Manāra (madrasiyya) (1899)"},
                        {"url":"./tabdd.html#t1r679","alias":"Al-Mashriq (1898)"},
                        {"url":"./tabdd.html#t1r63","alias":"Al-Mihmāz (1870)"},
                        {"url":"./tabdd.html#t1r114","alias":"Al-Mishkāt (c1877)"},
                        {"url":"./tabdd.html#t1r130","alias":"Al-Mishkāt (1878)"},
                        {"url":"./tabdd.html#t1r165","alias":"Al-Miṣbāḥ (1880)"},
                        {"url":"./tabdd.html#t1r616","alias":"Al-Munāẓir (1897)"},
                        {"url":"./tabdd.html#t1r104","alias":"Al-Muqtaṭaf (1876)"},
                        {"url":"./tabdd.html#t1r26","alias":"Nafīr Sūriyya/ Nafīr Sūriyya aw al-Waṭaniyya (1860)"},
                        {"url":"./tabdd.html#t1r423","alias":"Al-Nahḍa al-ʿUsbūʿiyya (1893)"},
                        {"url":"./tabdd.html#t1r65","alias":"Al-Naḥla (1870)"},
                        {"url":"./tabdd.html#t1r91","alias":"Al-Naḥla al-Fatiya (1874)"},
                        {"url":"./tabdd.html#t1r73","alias":"Al-Naḥla wa’l-Zahra (1871)"},
                        {"url":"./tabdd.html#t1r75","alias":"Al-Najāḥ (1871)"},
                        {"url":"./tabdd.html#t1r559","alias":"Al-Nashāt (Madrasiyya) (1896)"},
                        {"url":"./tabdd.html#t1r39","alias":"Al-Nashra al-Shahriyya (1866)"},
                        {"url":"./tabdd.html#t1r76","alias":"Al-Nashra al-Usbūʿiyya (1871)"},
                        {"url":"./tabdd.html#t1r428","alias":"Al-Rawḍa (1893)"},
                        {"url":"./tabdd.html#t1r763","alias":"Rawḍat al-Maʿārif (1899)"},
                        {"url":"./tabdd.html#t1r309","alias":"Al-Riwāyāt al-Aṣriyya (1888)"},
                        {"url":"./tabdd.html#t1r40","alias":"Al-Sharika al-Shaḥriyya (1866)"},
                        {"url":"./tabdd.html#t1r239","alias":"Silsilat al-Fukāhāt fī Aṭāyib al-Riwāyāt (1884)"},
                        {"url":"./tabdd.html#t1r830","alias":"Ṣadā Lubnān (1900)"},
                        {"url":"./tabdd.html#t1r334","alias":"Al-Ṣafā (1889)"},
                        {"url":"./tabdd.html#t1r270","alias":"Al-Ṣafāʾ (1886)"},
                        {"url":"./tabdd.html#t1r94","alias":"Al-Taqaddum (1874)"},
                        {"url":"./tabdd.html#t1r135","alias":"Al-Taqaddum (1878)"},
                        {"url":"./tabdd.html#t1r848","alias":"Thamarāt al-Adhhān (1899)"},
                        {"url":"./tabdd.html#t1r98","alias":"Thamarāt al-Funūn (1875)"},
                        {"url":"./tabdd.html#t1r134","alias":"Al-Ṭabīb (1878)"},
                        {"url":"./tabdd.html#t1r68","alias":"Al-Zahra (1870)"},
                        {"url":"./tabdd.html#t1r777","alias":"Zahrat al-Kulliyya (1899)"}]},
                {
            "label":"Bombay",
            "type":"city",
            "latlng":"19.07283, 72.88261",
            "periodicals":"1",
            "links":
            [ {"url":"./tabdd.html#t1r15","alias":"Doresh Tov le-ʿAmmo/ Ṭālib al-Khayr li-Qawmi-hi/The Hebrew Gazette (1855)"}]},
                {
            "label":"Boston",
            "type":"city",
            "latlng":"42.35843, -71.05977",
            "periodicals":"1",
            "links":
            [ {"url":"./tabdd.html#t2r848","alias":"Al-Bustān (?)"}]},
                {
            "label":"Brazil",
            "type":"country",
            "latlng":"-10, -55",
            "periodicals":"7",
            "links":
            [ {"url":"./tabdd.html#t1r781","alias":"Al-ʿAdl (1900)"},
                        {"url":"./tabdd.html#t1r780","alias":"Abū Nuwās (1900)"},
                        {"url":"./tabdd.html#t1r533","alias":"Al-Barāzil (1896)"},
                        {"url":"./tabdd.html#t1r444","alias":"Al-Fayḥāʾ (1894)"},
                        {"url":"./tabdd.html#t1r565","alias":"Al-Raqīb (1896)"},
                        {"url":"./tabdd.html#t1r836","alias":"Al-Shaʿb (1900)"},
                        {"url":"./tabdd.html#t1r834","alias":"Al-Ṣawāb (1900)"}]},
                {
            "label":"Buenos Aires",
            "type":"city",
            "latlng":"-34.61315, -58.37723",
            "periodicals":"7",
            "links":
            [ {"url":"./tabdd.html#t1r769","alias":"al-Ṣubḥ (1899)"},
                        {"url":"./tabdd.html#t1r450","alias":"Al-Jarīda (1894)"},
                        {"url":"./tabdd.html#t1r704","alias":"Al-Sāʿiqa (1898)"},
                        {"url":"./tabdd.html#t1r765","alias":"Ṣadā al-Janūb (1899)"},
                        {"url":"./tabdd.html#t1r471","alias":"Ṣawt al-Fayḥāʾ (1894)"},
                        {"url":"./tabdd.html#t1r835","alias":"Al-Ṣidq (1900)"},
                        {"url":"./tabdd.html#t1r772","alias":"Al-Tamaddun (1899)"}]},
                {
            "label":"Būlāq",
            "type":"town",
            "latlng":"36.56273, 67.81999",
            "periodicals":"1",
            "links":
            [ {"url":"./tabdd.html#t1r5","alias":"Waqāʾiʿ-i Miṣriyye/Waqāyiʿ Miṣriyya (1828)"}]},
                {
            "label":"Cagliari, Sardinia",
            "type":"city",
            "latlng":"39.223841, 9.121661",
            "periodicals":"2",
            "links":
            [ {"url":"./tabdd.html#t1r168","alias":"Al-Mustaqbal (1880)"},
                        {"url":"./tabdd.html#t1r169","alias":"Al-Mustaqill (1880)"}]},
                {
            "label":"Cairo",
            "type":"city",
            "latlng":"30.06263, 31.24967",
            "periodicals":"379",
            "links":
            [ {"url":"./tabdd.html#t1r260","alias":"Al-ʿAdāla (1886)"},
                        {"url":"./tabdd.html#t1r582","alias":"Al-ʿAdāla (1897)"},
                        {"url":"./tabdd.html#t1r480","alias":"Al-ʿAdl (1895)"},
                        {"url":"./tabdd.html#t1r440","alias":"Al-ʿAlam (1894)"},
                        {"url":"./tabdd.html#t1r584","alias":"Al-ʿAlam al-ʿUthmānī (1897)"},
                        {"url":"./tabdd.html#t1r404","alias":"Al-ʿAlam al-Miṣrī (1893)"},
                        {"url":"./tabdd.html#t1r784","alias":"Al-ʿArab (1900)"},
                        {"url":"./tabdd.html#t1r585","alias":"ʿArāʾid al-Miṣrī (1897)"},
                        {"url":"./tabdd.html#t1r531","alias":"Al-ʿAṣr al-ʿAbbāsī (1896)"},
                        {"url":"./tabdd.html#t1r785","alias":"Al-ʿAṣr al-Jadīd (1900)"},
                        {"url":"./tabdd.html#t1r586","alias":"Al-ʿAṭar/al-ʿAṭṭār (1897)"},
                        {"url":"./tabdd.html#t1r719","alias":"Al-ʿĀʾila (1899)"},
                        {"url":"./tabdd.html#t1r482","alias":"Al-ʿĀm al-Jadīd (1895)"},
                        {"url":"./tabdd.html#t1r600","alias":"Al-ʿIfrīt (1897)"},
                        {"url":"./tabdd.html#t1r447","alias":"Al-ʿIlm (1894)"},
                        {"url":"./tabdd.html#t1r575","alias":"Al-ʿUmda (1896)"},
                        {"url":"./tabdd.html#t1r247","alias":"Al-Aʿlām (1885)"},
                        {"url":"./tabdd.html#t1r14","alias":"Aʿmāl al-Rayy (1855)"},
                        {"url":"./tabdd.html#t1r580","alias":"Abu’l-ʿIyāl (1897)"},
                        {"url":"./tabdd.html#t1r403","alias":"Abu’l-Hawl (1893)"},
                        {"url":"./tabdd.html#t1r720","alias":"Abu’l-Hudā (1898)"},
                        {"url":"./tabdd.html#t1r581","alias":"Abū Naẓẓāra Muʿaẓẓama (1897)"},
                        {"url":"./tabdd.html#t1r108","alias":"Abū Naẓẓāra Zarqā (1877)"},
                        {"url":"./tabdd.html#t1r640","alias":"Al-Afkār (1898)"},
                        {"url":"./tabdd.html#t1r782","alias":"Al-Afkār (1900)"},
                        {"url":"./tabdd.html#t1r438","alias":"Al-Ahālī (1894)"},
                        {"url":"./tabdd.html#t1r100","alias":"Al-Ahrām (1876)"},
                        {"url":"./tabdd.html#t1r277","alias":"Al-Aḥkām (1887)"},
                        {"url":"./tabdd.html#t1r439","alias":"Al-Aḥkām (1894)"},
                        {"url":"./tabdd.html#t1r289","alias":"Al-Aḥkām al-Miṣriyya (1888)"},
                        {"url":"./tabdd.html#t1r583","alias":"Al-Ajyāl (1897)"},
                        {"url":"./tabdd.html#t1r529","alias":"Al-Akhbār (1896)"},
                        {"url":"./tabdd.html#t1r722","alias":"Anīn Maẓlūm (1899)"},
                        {"url":"./tabdd.html#t1r642","alias":"Anīs al-Jalīs (1898)"},
                        {"url":"./tabdd.html#t1r643","alias":"Anīs al-Tilmīdh (1898)"},
                        {"url":"./tabdd.html#t1r530","alias":"Al-Aqlām (1896)"},
                        {"url":"./tabdd.html#t1r441","alias":"Al-Arghūl (1894)"},
                        {"url":"./tabdd.html#t1r845","alias":"Al-Arghūl (1894)"},
                        {"url":"./tabdd.html#t1r644","alias":"Asad (1898)"},
                        {"url":"./tabdd.html#t1r723","alias":"Al-Asad al-Murqusī (1899)"},
                        {"url":"./tabdd.html#t1r724","alias":"Al-Asās al-ʿIlmī (1899)"},
                        {"url":"./tabdd.html#t1r587","alias":"Al-Athar (1897)"},
                        {"url":"./tabdd.html#t2r847","alias":"Al-Awlād (?)"},
                        {"url":"./tabdd.html#t1r786","alias":"Ayn Shams (1900)"},
                        {"url":"./tabdd.html#t1r278","alias":"Al-Azhar (1889)"},
                        {"url":"./tabdd.html#t1r276","alias":"Al-Ādāb (1887)"},
                        {"url":"./tabdd.html#t1r313","alias":"Al-Ādāb (1889)"},
                        {"url":"./tabdd.html#t1r787","alias":"Al-Badr al-Munīr (1900)"},
                        {"url":"./tabdd.html#t1r647","alias":"Baghula / Baghlat al-ʿUshr/Baghlit al-ʿIshar (1898)"},
                        {"url":"./tabdd.html#t1r589","alias":"Al-Banāna (1897)"},
                        {"url":"./tabdd.html#t1r485","alias":"Al-Barīd (1895)"},
                        {"url":"./tabdd.html#t1r486","alias":"Al-Barq (1895)"},
                        {"url":"./tabdd.html#t1r487","alias":"Baṣīr al-Sharq (1895)"},
                        {"url":"./tabdd.html#t1r231","alias":"Al-Bayān (1884)"},
                        {"url":"./tabdd.html#t1r592","alias":"Al-Bayān (1897)"},
                        {"url":"./tabdd.html#t1r726","alias":"Al-Bayān (1899)"},
                        {"url":"./tabdd.html#t1r532","alias":"Bāb al-Futūḥ (1896)"},
                        {"url":"./tabdd.html#t1r590","alias":"Al-Bāshā (1897)"},
                        {"url":"./tabdd.html#t1r180","alias":"Al-Burhān (1881)"},
                        {"url":"./tabdd.html#t1r219","alias":"Al-Burhān (1883)"},
                        {"url":"./tabdd.html#t1r728","alias":"Al-Burṣa al-Miṣriyya (1899)"},
                        {"url":"./tabdd.html#t1r369","alias":"Al-Bustān (1892)"},
                        {"url":"./tabdd.html#t1r141","alias":"Bustān al-Akhbār (1879)"},
                        {"url":"./tabdd.html#t1r127","alias":"Al-Būsfūr / Le Bosphore égyptien (1878)"},
                        {"url":"./tabdd.html#t1r594","alias":"Al-Būsta (1897)"},
                        {"url":"./tabdd.html#t1r790","alias":"Al-Būstā (1900)"},
                        {"url":"./tabdd.html#t1r534","alias":"Al-Daḥḥ (1896)"},
                        {"url":"./tabdd.html#t1r314","alias":"Dalīl al-Barīd al-Miṣrī (1889)"},
                        {"url":"./tabdd.html#t1r315","alias":"Dalīl al-Mufīd fi Ashghāl al-Barīd (1889)"},
                        {"url":"./tabdd.html#t1r353","alias":"Dalīl Wādī al-Nīl (1891)"},
                        {"url":"./tabdd.html#t1r792","alias":"Al-Dawāʾ (1900)"},
                        {"url":"./tabdd.html#t1r793","alias":"Al-Dunyā fī Bāris (1900)"},
                        {"url":"./tabdd.html#t1r651","alias":"Al-Ḍiyāʾ (1898)"},
                        {"url":"./tabdd.html#t1r249","alias":"Al-Fallāh (1885)"},
                        {"url":"./tabdd.html#t1r182","alias":"Al-Fallāh / Le Cultivateur (1881)"},
                        {"url":"./tabdd.html#t1r354","alias":"Al-Farāʾid (1891)"},
                        {"url":"./tabdd.html#t1r371","alias":"Al-Farāʾid (1892)"},
                        {"url":"./tabdd.html#t1r652","alias":"Faṣl al-Khiṭāb (1898)"},
                        {"url":"./tabdd.html#t1r372","alias":"Al-Fatā (1892)"},
                        {"url":"./tabdd.html#t1r355","alias":"Al-Fawāʾid al-Ṣiḥḥiyya (1891)"},
                        {"url":"./tabdd.html#t1r318","alias":"Fawākih al-Arwāḥ (1889)"},
                        {"url":"./tabdd.html#t1r729","alias":"Al-Fawḍā (1899)"},
                        {"url":"./tabdd.html#t1r654","alias":"Al-Filāḥa al-Miṣriyya (1898)"},
                        {"url":"./tabdd.html#t1r319","alias":"Al-Firdaws (1889)"},
                        {"url":"./tabdd.html#t1r537","alias":"Al-Firdaws (1896)"},
                        {"url":"./tabdd.html#t1r653","alias":"Al-Fīl al-Abyaḍ (1898)"},
                        {"url":"./tabdd.html#t1r655","alias":"Al-Fukāha (1898)"},
                        {"url":"./tabdd.html#t1r374","alias":"Furṣat al-Awqāt (1892)"},
                        {"url":"./tabdd.html#t1r205","alias":"Al-Fusṭāṭ (1882)"},
                        {"url":"./tabdd.html#t1r538","alias":"Al-Ghazāla (1896)"},
                        {"url":"./tabdd.html#t1r657","alias":"Al-Ghazāla (1898)"},
                        {"url":"./tabdd.html#t1r795","alias":"Al-Ghazāla (1900)"},
                        {"url":"./tabdd.html#t1r731","alias":"Ghazl al-Banāt (1899)"},
                        {"url":"./tabdd.html#t1r595","alias":"Al-Ghirbāl (1897)"},
                        {"url":"./tabdd.html#t1r798","alias":"Al-Hawānīm (1900)"},
                        {"url":"./tabdd.html#t1r539","alias":"Al-Hidāya (1896)"},
                        {"url":"./tabdd.html#t1r597","alias":"Al-Hidāya (1897)"},
                        {"url":"./tabdd.html#t1r598","alias":"Al-Hidāya al-ʿĀmma (1897)"},
                        {"url":"./tabdd.html#t1r375","alias":"Al-Hilāl (1892)"},
                        {"url":"./tabdd.html#t1r409","alias":"Al-Hudā (1893)"},
                        {"url":"./tabdd.html#t1r96","alias":"Ḥadīqat al-Abṣār (1875)"},
                        {"url":"./tabdd.html#t1r206","alias":"Al-Ḥaḍāra (1882)"},
                        {"url":"./tabdd.html#t1r797","alias":"Al-Ḥammāra (1900)"},
                        {"url":"./tabdd.html#t1r109","alias":"Ḥaqīqat al-Akhbār (1877)"},
                        {"url":"./tabdd.html#t1r491","alias":"Al-Ḥaqq (1895)"},
                        {"url":"./tabdd.html#t1r9","alias":"Al-Ḥawādith al-Tijāriyya wa’l-Iʿlānāt al-Malikiyya (1848)"},
                        {"url":"./tabdd.html#t1r338","alias":"Al-Ḥākim (1890)"},
                        {"url":"./tabdd.html#t1r596","alias":"Al-Ḥākim (1897)"},
                        {"url":"./tabdd.html#t1r185","alias":"Al-Ḥijāz (1881)"},
                        {"url":"./tabdd.html#t1r735","alias":"Ḥimārat Munyatī (1899)"},
                        {"url":"./tabdd.html#t1r541","alias":"Al-Ḥudūd (1896)"},
                        {"url":"./tabdd.html#t1r251","alias":"Al-Ḥuqūq (1885)"},
                        {"url":"./tabdd.html#t1r542","alias":"Al-Ḥurriyya (1896)"},
                        {"url":"./tabdd.html#t1r661","alias":"Al-Ḥurūb (1898)"},
                        {"url":"./tabdd.html#t1r356","alias":"Al-Iʿlan (1891)"},
                        {"url":"./tabdd.html#t1r376","alias":"Al-Iʿlān (1892)"},
                        {"url":"./tabdd.html#t1r207","alias":"Al-Iʿtidāl (1882)"},
                        {"url":"./tabdd.html#t1r736","alias":"Idrīs (1899)"},
                        {"url":"./tabdd.html#t1r783","alias":"Al-Ikhāʾ (1900)"},
                        {"url":"./tabdd.html#t1r493","alias":"Al-Ikhlāṣ (1895)"},
                        {"url":"./tabdd.html#t1r410","alias":"Al-Iltifāt (1893)"},
                        {"url":"./tabdd.html#t1r799","alias":"Al-Indhār (1900)"},
                        {"url":"./tabdd.html#t1r800","alias":"Al-Insāniyya (1900)"},
                        {"url":"./tabdd.html#t1r494","alias":"Al-Inṣāf (1895)"},
                        {"url":"./tabdd.html#t1r801","alias":"Al-Intiqād al-ʿĀmm (1900)"},
                        {"url":"./tabdd.html#t1r448","alias":"Al-Islām (1894)"},
                        {"url":"./tabdd.html#t1r602","alias":"Al-Istiqāma (1897)"},
                        {"url":"./tabdd.html#t1r377","alias":"Al-Iṣlāḥ (1892)"},
                        {"url":"./tabdd.html#t1r603","alias":"Al-Ittiḥād al-Islāmī / L’Union Islamique (1897)"},
                        {"url":"./tabdd.html#t1r604","alias":"Al-Jalāʾ (1897)"},
                        {"url":"./tabdd.html#t1r85","alias":"Jarīdat Arkān Ḥarb al-Jaysh al-Miṣrī (1873)"},
                        {"url":"./tabdd.html#t1r6","alias":"Al-Jarīda al-ʿAskariyya (1834)"},
                        {"url":"./tabdd.html#t1r35","alias":"Al-Jarīda al-ʿAskariyya al-Miṣriyya (1865)"},
                        {"url":"./tabdd.html#t1r297","alias":"Al-Jarīda al-Miṣriyya (1888)"},
                        {"url":"./tabdd.html#t1r25","alias":"Al-Jawāʾib (1860)"},
                        {"url":"./tabdd.html#t1r663","alias":"Al-Jāsūs (1898)"},
                        {"url":"./tabdd.html#t1r665","alias":"Juhayna (1898)"},
                        {"url":"./tabdd.html#t1r80","alias":"Jūrnāl ʿUmūmī li-Kāfat al-Iʿlānāt/Journal Général de Publicité (1872)"},
                        {"url":"./tabdd.html#t1r3","alias":"Al-Jūrnāl al-Khudaywī / al-Khidīwī (1813)"},
                        {"url":"./tabdd.html#t1r607","alias":"Al-Kahrubāʾiyya (1897)"},
                        {"url":"./tabdd.html#t1r412","alias":"Al-Kamāl (1893)"},
                        {"url":"./tabdd.html#t1r544","alias":"Al-Kamāl (1896)"},
                        {"url":"./tabdd.html#t1r803","alias":"Al-Kanīsa (1900)"},
                        {"url":"./tabdd.html#t1r146","alias":"Kanz al-Zirāʿa (1879)"},
                        {"url":"./tabdd.html#t1r358","alias":"Kanz al-Zirāʿa (1891)"},
                        {"url":"./tabdd.html#t1r608","alias":"Al-Kawkab al-Durrī (1897)"},
                        {"url":"./tabdd.html#t1r147","alias":"Al-Kawkab al-Miṣrī (1879)"},
                        {"url":"./tabdd.html#t1r545","alias":"Al-Kawthar (1896)"},
                        {"url":"./tabdd.html#t1r746","alias":"Al-Kawthar (1899)"},
                        {"url":"./tabdd.html#t1r804","alias":"Al-Khabīr (1900)"},
                        {"url":"./tabdd.html#t1r667","alias":"Al-Khayla al-Kadhdhāba (1898)"},
                        {"url":"./tabdd.html#t1r805","alias":"Al-Khizāna (1900)"},
                        {"url":"./tabdd.html#t1r496","alias":"Al-Kināna (1895)"},
                        {"url":"./tabdd.html#t1r546","alias":"Al-Kurbāj wa’l-Ifrīt (1896)"},
                        {"url":"./tabdd.html#t1r668","alias":"Kurdistān (1898)"},
                        {"url":"./tabdd.html#t1r263","alias":"Al-Laṭāʾif (1886)"},
                        {"url":"./tabdd.html#t1r1","alias":"La décade égyptienne (1799)"},
                        {"url":"./tabdd.html#t1r126","alias":"Le Bavard Egyptien (1878)"},
                        {"url":"./tabdd.html#t1r669","alias":"Al-Lijām (1898)"},
                        {"url":"./tabdd.html#t1r453","alias":"Lisān al-ʿArab (1894)"},
                        {"url":"./tabdd.html#t1r807","alias":"Al-Liwāʾ (1900)"},
                        {"url":"./tabdd.html#t1r497","alias":"Al-Maʿārif (1895)"},
                        {"url":"./tabdd.html#t1r610","alias":"Al-Maʿārif (1897)"},
                        {"url":"./tabdd.html#t1r671","alias":"Al-Maʿārif (1898)"},
                        {"url":"./tabdd.html#t1r672","alias":"Al-Maʿhadī (1898)"},
                        {"url":"./tabdd.html#t1r612","alias":"Al-Maʾmūn (1897)"},
                        {"url":"./tabdd.html#t1r748","alias":"Al-Madāris (1899)"},
                        {"url":"./tabdd.html#t1r414","alias":"Al-Madrasa (1893)"},
                        {"url":"./tabdd.html#t1r673","alias":"Al-Mahdī (1898)"},
                        {"url":"./tabdd.html#t1r342","alias":"Al-Maḥākim (1890)"},
                        {"url":"./tabdd.html#t1r454","alias":"Al-Maḥāsin (1894)"},
                        {"url":"./tabdd.html#t1r113","alias":"Al-Maḥrūsa (1877)"},
                        {"url":"./tabdd.html#t1r674","alias":"Majallat al-Jamʿiyya al-Ṭibbiyya al-Miṣriyya (1898)"},
                        {"url":"./tabdd.html#t1r751","alias":"Majallat al-Jamʿiyya al-Zirāʿiyya al-Khudaywiyya (1899)"},
                        {"url":"./tabdd.html#t1r808","alias":"Majallat al-Liwāʾ (1900)"},
                        {"url":"./tabdd.html#t1r809","alias":"Majallat al-Majallāt al-ʿArabiyya (1900)"},
                        {"url":"./tabdd.html#t1r456","alias":"Majallat Miṣr/Miṣr (1894)"},
                        {"url":"./tabdd.html#t1r810","alias":"Al-Majalla al-Miṣriyya (1900)"},
                        {"url":"./tabdd.html#t1r455","alias":"Al-Majalla al-Zirāʿiyya wa’l-ʿAdl (1894)"},
                        {"url":"./tabdd.html#t1r811","alias":"Al-Majmūʿa al-Rasmiyya li’l-Maḥākim al-Ahliyya (1900)"},
                        {"url":"./tabdd.html#t1r282","alias":"Makārim al-Akhlāq (1887)"},
                        {"url":"./tabdd.html#t1r812","alias":"Makārim al-Akhlāq al-Islāmiyya (1900)"},
                        {"url":"./tabdd.html#t1r678","alias":"Al-Manār (1898)"},
                        {"url":"./tabdd.html#t1r500","alias":"Manfīs / Memphis (1895)"},
                        {"url":"./tabdd.html#t1r380","alias":"Al-Manẓūm (1892)"},
                        {"url":"./tabdd.html#t1r680","alias":"Al-Masīḥ al-Dajjāl (1898)"},
                        {"url":"./tabdd.html#t1r681","alias":"Al-Maṭālib al-Ḥaqqa (1898)"},
                        {"url":"./tabdd.html#t1r682","alias":"Al-Mawsūʿāt (1898)"},
                        {"url":"./tabdd.html#t1r149","alias":"Al-Maymūn (1879)"},
                        {"url":"./tabdd.html#t1r613","alias":"Al-Maymūn (1897)"},
                        {"url":"./tabdd.html#t1r683","alias":"Maẓallat Dāwūd (1898)"},
                        {"url":"./tabdd.html#t1r814","alias":"Al-Miftāḥ (1900)"},
                        {"url":"./tabdd.html#t1r684","alias":"Al-Minkhās (1898)"},
                        {"url":"./tabdd.html#t1r502","alias":"Al-Miqyās (1895)"},
                        {"url":"./tabdd.html#t1r16","alias":"Mirʾāt al-Aḥwāl (1855)"},
                        {"url":"./tabdd.html#t1r614","alias":"Mirʾāt al-Aṣr (1897)"},
                        {"url":"./tabdd.html#t1r551","alias":"Mirʾāt al-Ḥasnāʾ (1896)"},
                        {"url":"./tabdd.html#t1r150","alias":"Mirʾāt al-Sharq (1879)"},
                        {"url":"./tabdd.html#t1r210","alias":"Mirʾāt al-Sharq (1882)"},
                        {"url":"./tabdd.html#t1r224","alias":"Mirʾāt al-Sharq (1883)"},
                        {"url":"./tabdd.html#t1r685","alias":"Al-Mirṣād (1898)"},
                        {"url":"./tabdd.html#t1r816","alias":"Al-Miṣbāḥ al-Jadīd (1900)"},
                        {"url":"./tabdd.html#t1r686","alias":"Miṣbāḥ al-Sharq (1898)"},
                        {"url":"./tabdd.html#t1r115","alias":"Miṣr (1877)"},
                        {"url":"./tabdd.html#t1r189","alias":"Miṣr (1881)"},
                        {"url":"./tabdd.html#t1r461","alias":"Miṣr (1894)"},
                        {"url":"./tabdd.html#t1r503","alias":"Miṣr (1895)"},
                        {"url":"./tabdd.html#t1r416","alias":"Al-Mīzān (1893)"},
                        {"url":"./tabdd.html#t1r166","alias":"Mīzāniyyat al-Dawla al-Miṣriyya (1880)"},
                        {"url":"./tabdd.html#t1r328","alias":"Al-Muʾayyad (1889)"},
                        {"url":"./tabdd.html#t1r689","alias":"Al-Muʿtaṣim (1898)"},
                        {"url":"./tabdd.html#t1r552","alias":"Al-Mubashshir al-Miṣrī (1896)"},
                        {"url":"./tabdd.html#t1r191","alias":"Al-Mufīd (1881)"},
                        {"url":"./tabdd.html#t1r167","alias":"Mufradāt Mīzāniyyat al-Ḥukūma al-Miṣriyya (1880)"},
                        {"url":"./tabdd.html#t1r417","alias":"Al-Muhandis (1893)"},
                        {"url":"./tabdd.html#t1r688","alias":"Al-Muḥāmī (1898)"},
                        {"url":"./tabdd.html#t1r283","alias":"Al-Mukhbir al-Miṣrī (1887)"},
                        {"url":"./tabdd.html#t1r553","alias":"Al-Munabbih (1896)"},
                        {"url":"./tabdd.html#t1r64","alias":"Al-Munabbih al-Tijārī al-Miṣrī / Indicateur Commercial (1870)"},
                        {"url":"./tabdd.html#t1r504","alias":"Al-Munādama (1895)"},
                        {"url":"./tabdd.html#t1r554","alias":"Al-Munādama (1896)"},
                        {"url":"./tabdd.html#t1r555","alias":"Al-Munīr (1896)"},
                        {"url":"./tabdd.html#t1r194","alias":"Al-Muntakhab (1881)"},
                        {"url":"./tabdd.html#t1r462","alias":"Muntakhabāt al-Riwāyāt (1894)"},
                        {"url":"./tabdd.html#t1r418","alias":"Al-Muntaqid (1893)"},
                        {"url":"./tabdd.html#t1r505","alias":"Al-Muntazah (1895)"},
                        {"url":"./tabdd.html#t1r329","alias":"Al-Muqaṭṭam (1889)"},
                        {"url":"./tabdd.html#t1r330","alias":"Al-Muqaṭṭam al-Usbūʿī (1889)"},
                        {"url":"./tabdd.html#t1r104","alias":"Al-Muqtaṭaf (1876)"},
                        {"url":"./tabdd.html#t1r419","alias":"Al-Murshid (1893)"},
                        {"url":"./tabdd.html#t1r556","alias":"Al-Murshid (1896)"},
                        {"url":"./tabdd.html#t1r463","alias":"Al-Mushīr/ The Counsellor (1894)"},
                        {"url":"./tabdd.html#t1r758","alias":"Al-Mustashār (1899)"},
                        {"url":"./tabdd.html#t1r421","alias":"Al-Mutanaffidh (1893)"},
                        {"url":"./tabdd.html#t1r422","alias":"Al-Nadīm (1893)"},
                        {"url":"./tabdd.html#t1r817","alias":"Al-Nadīm (1900)"},
                        {"url":"./tabdd.html#t1r818","alias":"Al-Nahḍa al-Adabiyya (1900)"},
                        {"url":"./tabdd.html#t1r558","alias":"Al-Nahj al-Qawīm (1896)"},
                        {"url":"./tabdd.html#t1r506","alias":"Al-Naḥla (1895)"},
                        {"url":"./tabdd.html#t1r74","alias":"Al-Naḥla al-Ḥurra (1871)"},
                        {"url":"./tabdd.html#t1r196","alias":"Al-Najāḥ (1881)"},
                        {"url":"./tabdd.html#t1r618","alias":"Al-Najāt (1897)"},
                        {"url":"./tabdd.html#t1r619","alias":"Al-Nashʾa al-Waṭaniyya (1897)"},
                        {"url":"./tabdd.html#t1r620","alias":"Nashrat al-ʿAdāla (1897)"},
                        {"url":"./tabdd.html#t1r171","alias":"Nashrat al-Sharika al-Zirāʿiyya al-Miṣriyya/ Bulletin Société Egyptienne d’Agriculture (1880)"},
                        {"url":"./tabdd.html#t1r622","alias":"Al-Nashra al-ʿUthmāniyya (1897)"},
                        {"url":"./tabdd.html#t1r385","alias":"Al-Nashra al-Dīniyya al-Usbūʿiyya (1892)"},
                        {"url":"./tabdd.html#t1r424","alias":"Al-Nashra al-Dīniyya al-Usbūʿiyya (1893)"},
                        {"url":"./tabdd.html#t1r621","alias":"Al-Nashra al-Idāriyya (1897)"},
                        {"url":"./tabdd.html#t1r386","alias":"Al-Nashra al-Injīliyya al-Miṣriyya (1892)"},
                        {"url":"./tabdd.html#t1r425","alias":"Al-Nashra al-Injīliyya al-Usbūʿiyya (1893)"},
                        {"url":"./tabdd.html#t1r254","alias":"Al-Nashra al-Rasmiyya li-Maṣlaḥat al-Barīd/Al-Nashra al-Barīdiyya (1885)"},
                        {"url":"./tabdd.html#t1r213","alias":"Al-Nashra al-Sanawiyya ʿan al-Tijāra al-Khārijiyya / Le Commerce Extérieur de l’Égypte (1882?)"},
                        {"url":"./tabdd.html#t1r560","alias":"Al-Nashra al-Shaḥriyya (1896)"},
                        {"url":"./tabdd.html#t1r331","alias":"Al-Nashra al-Usbūʿiyya ʿan al-Mawālid wa’l-Wafayāt wa’l-Amrāḍ al-Maʿdiyya (1889)"},
                        {"url":"./tabdd.html#t1r690","alias":"Al-Naṣīb (1898)"},
                        {"url":"./tabdd.html#t1r623","alias":"Al-Naṣr (1897)"},
                        {"url":"./tabdd.html#t1r389","alias":"Al-Naṣūḥ (1892)"},
                        {"url":"./tabdd.html#t1r819","alias":"Al-Naẓẓāra (1900)"},
                        {"url":"./tabdd.html#t1r507","alias":"Al-Nāẓūr al-Miṣrī (1895)"},
                        {"url":"./tabdd.html#t1r508","alias":"Al-Nibrās (1895)"},
                        {"url":"./tabdd.html#t1r285","alias":"Al-Nīl (1887)"},
                        {"url":"./tabdd.html#t1r363","alias":"Al-Nīl (1891)"},
                        {"url":"./tabdd.html#t1r131","alias":"Al-Nīl; Il Nilo, Le Nile (1878)"},
                        {"url":"./tabdd.html#t1r66","alias":"Nuzhat al-Afkār (1870)"},
                        {"url":"./tabdd.html#t1r761","alias":"Al-Nūr (1899)"},
                        {"url":"./tabdd.html#t1r305","alias":"Al-Nūr al-Tawfīqī (1888)"},
                        {"url":"./tabdd.html#t1r692","alias":"Al-Qamr (1898)"},
                        {"url":"./tabdd.html#t1r510","alias":"Qarāʾin al-Aḥwāl (1895)"},
                        {"url":"./tabdd.html#t1r694","alias":"Al-Qawl al-Ḥaqq (1898)"},
                        {"url":"./tabdd.html#t1r268","alias":"Al-Qāhira (1886)"},
                        {"url":"./tabdd.html#t1r306","alias":"Al-Qāhira (1888)"},
                        {"url":"./tabdd.html#t1r332","alias":"Al-Qāhira (1889)"},
                        {"url":"./tabdd.html#t1r256","alias":"Al-Qāhira al-Ḥurra (1885)"},
                        {"url":"./tabdd.html#t1r561","alias":"Al-Qāhira al-Ḥurra (1896)"},
                        {"url":"./tabdd.html#t1r255","alias":"Al-Qāhira (al-Ḥurra) (1885)"},
                        {"url":"./tabdd.html#t1r693","alias":"Al-Qānūn al-Asāsī (1898)"},
                        {"url":"./tabdd.html#t1r822","alias":"Al-Quds (1900)"},
                        {"url":"./tabdd.html#t1r426","alias":"Raʿmsīs (1893)"},
                        {"url":"./tabdd.html#t1r391","alias":"Al-Raʾy al-ʿĀmm (1892)"},
                        {"url":"./tabdd.html#t1r392","alias":"Al-Rashād (1892)"},
                        {"url":"./tabdd.html#t1r625","alias":"Al-Rassām (1897)"},
                        {"url":"./tabdd.html#t1r825","alias":"Al-Rasūl (1900)"},
                        {"url":"./tabdd.html#t1r93","alias":"Rawḍat al-Akhbār (1874)"},
                        {"url":"./tabdd.html#t1r67","alias":"Rawḍat al-Madāris al-Miṣriyya (1870)"},
                        {"url":"./tabdd.html#t1r624","alias":"Rāʾid al-Layl (1897)"},
                        {"url":"./tabdd.html#t1r563","alias":"Al-Rāʾid al-Miṣrī (1896)"},
                        {"url":"./tabdd.html#t1r695","alias":"Al-Rāʾid al-Miṣrī (1898)"},
                        {"url":"./tabdd.html#t1r823","alias":"Rāʾid al-Nīl (1900)"},
                        {"url":"./tabdd.html#t1r564","alias":"Al-Rāʾid al-Ṭibbī (1896)"},
                        {"url":"./tabdd.html#t1r393","alias":"Al-Rāwī (1892)"},
                        {"url":"./tabdd.html#t2r857","alias":"Al-Riwāyāt al-Muṣawwara (?)"},
                        {"url":"./tabdd.html#t2r858","alias":"Al-Riwāyāt al-Qiṣaṣiyya (?)"},
                        {"url":"./tabdd.html#t1r566","alias":"Al-Riyāḍa (1896)"},
                        {"url":"./tabdd.html#t1r310","alias":"Al-Riyāḍ al-Miṣriyya/Al-Riyāḍ al-Sūriyya (1888)"},
                        {"url":"./tabdd.html#t1r215","alias":"Al-Safīr (1882)"},
                        {"url":"./tabdd.html#t1r626","alias":"Al-Safīr (1897)"},
                        {"url":"./tabdd.html#t1r18","alias":"Al-Salṭana (1857)"},
                        {"url":"./tabdd.html#t1r628","alias":"Al-Salṭana (1897)"},
                        {"url":"./tabdd.html#t1r629","alias":"Al-Samīr al-Ṣaghīr (1897)"},
                        {"url":"./tabdd.html#t1r514","alias":"Al-Sayyār (1895)"},
                        {"url":"./tabdd.html#t1r515","alias":"Shahādat al-Ḥaqq (1895)"},
                        {"url":"./tabdd.html#t1r766","alias":"Al-Shahāma (1899)"},
                        {"url":"./tabdd.html#t1r706","alias":"Al-Shahbāʾ (1898)"},
                        {"url":"./tabdd.html#t1r472","alias":"Al-Shams (1894)"},
                        {"url":"./tabdd.html#t1r707","alias":"Shams al-Ḥaqīqa (1898)"},
                        {"url":"./tabdd.html#t1r347","alias":"Al-Sharaf (1890)"},
                        {"url":"./tabdd.html#t1r516","alias":"Al-Sharaf (1895)"},
                        {"url":"./tabdd.html#t1r431","alias":"Al-Sharāʾiʿ (1893)"},
                        {"url":"./tabdd.html#t1r568","alias":"Al-Sharq (1896)"},
                        {"url":"./tabdd.html#t1r708","alias":"Al-Shayṭān (1898)"},
                        {"url":"./tabdd.html#t1r121","alias":"Al-Shāṭir al-Kaslān wa’l-Nāʾim al-Yaqẓān (1877)"},
                        {"url":"./tabdd.html#t1r271","alias":"Al-Shifāʾ (1886)"},
                        {"url":"./tabdd.html#t1r311","alias":"Al-Shuhra / La renommé (1888)"},
                        {"url":"./tabdd.html#t1r239","alias":"Silsilat al-Fukāhāt fī Aṭāyib al-Riwāyāt (1884)"},
                        {"url":"./tabdd.html#t1r432","alias":"Silsilat al-Fukāhāt (continuation of Beiruti edition 1884) (1893)"},
                        {"url":"./tabdd.html#t1r767","alias":"Silsilat al-Riwāyāt (1899)"},
                        {"url":"./tabdd.html#t1r59","alias":"Statistique de l'Égypte (1870)"},
                        {"url":"./tabdd.html#t1r833","alias":"Subūl al-Hudā (1900)"},
                        {"url":"./tabdd.html#t1r709","alias":"Al-Sūdān al-Miṣrī (1898)"},
                        {"url":"./tabdd.html#t1r700","alias":"Al-Ṣabāḥ (1898)"},
                        {"url":"./tabdd.html#t1r701","alias":"Al-Ṣadā al-Miṣrī (1898)"},
                        {"url":"./tabdd.html#t1r513","alias":"Ṣadā al-Sharq (1895)"},
                        {"url":"./tabdd.html#t1r703","alias":"Al-Ṣadīq (1898)"},
                        {"url":"./tabdd.html#t1r470","alias":"Ṣahyūn (1894)"},
                        {"url":"./tabdd.html#t1r627","alias":"Al-Ṣāʿiqa (1897)"},
                        {"url":"./tabdd.html#t1r269","alias":"Al-Ṣādiq (1886)"},
                        {"url":"./tabdd.html#t1r286","alias":"Al-Ṣiḥḥa (1887)"},
                        {"url":"./tabdd.html#t1r518","alias":"Ṣūq al-ʿAṣr (1895)"},
                        {"url":"./tabdd.html#t1r770","alias":"Ṣūq al-ʿAṣr (1899)"},
                        {"url":"./tabdd.html#t1r771","alias":"Al-Tadhkār (1899)"},
                        {"url":"./tabdd.html#t1r570","alias":"Al-Tafrīḥ (1896)"},
                        {"url":"./tabdd.html#t1r840","alias":"Al-Tamthīl (1900)"},
                        {"url":"./tabdd.html#t1r2","alias":"Al-Tanbīh (*1800)"},
                        {"url":"./tabdd.html#t1r227","alias":"Al-Taqaddum al-Miṣrī (1883)"},
                        {"url":"./tabdd.html#t1r434","alias":"Al-Taqaddum al-Miṣrī (1893)"},
                        {"url":"./tabdd.html#t1r10","alias":"Taqwīm al-Akhbār ʿan al-Ḥawādith al-Tijāriyya wa’l-Iʿlānāt al-Malikiyya (1848)"},
                        {"url":"./tabdd.html#t1r710","alias":"Al-Taqwīm al-Miṣrī (1898)"},
                        {"url":"./tabdd.html#t1r713","alias":"Tasliyat al-Khawāṭir (1898)"},
                        {"url":"./tabdd.html#t1r572","alias":"Al-Tawfīq (1896)"},
                        {"url":"./tabdd.html#t1r241","alias":"Al-Tayms al-Miṣrī / The Times of Egypt (1884)"},
                        {"url":"./tabdd.html#t1r839","alias":"Tāj al-Maʿārif (1900)"},
                        {"url":"./tabdd.html#t1r573","alias":"Al-Thabāt (1896)"},
                        {"url":"./tabdd.html#t1r841","alias":"Al-Thamarāt (1900)"},
                        {"url":"./tabdd.html#t1r574","alias":"Al-Thurayyā (1896)"},
                        {"url":"./tabdd.html#t1r474","alias":"Al-Tilighrāfāt al-Ḥaqīqiyya (1894)"},
                        {"url":"./tabdd.html#t1r521","alias":"Al-Tilighrāfāt al-Jadīda (1895)"},
                        {"url":"./tabdd.html#t1r635","alias":"Al-Tilighrāfāt al-Jadīda (1897)"},
                        {"url":"./tabdd.html#t1r436","alias":"Al-Tilmīdh (1893)"},
                        {"url":"./tabdd.html#t1r636","alias":"Turkiyā (1897)"},
                        {"url":"./tabdd.html#t1r520","alias":"Ṭabīb al-ʿĀʾila wa Murshid al-Labīb ʿind Ghiyāb al-Ṭabīb (1895)"},
                        {"url":"./tabdd.html#t1r571","alias":"Ṭanṭā (1896)"},
                        {"url":"./tabdd.html#t1r631","alias":"Ṭanṭā (1897)"},
                        {"url":"./tabdd.html#t1r197","alias":"Al-Ṭāʾif (1881)"},
                        {"url":"./tabdd.html#t1r272","alias":"Al-Ṭāʾif (1886)"},
                        {"url":"./tabdd.html#t1r475","alias":"Al-Umma (1894)"},
                        {"url":"./tabdd.html#t1r476","alias":"Al-Urjul (1894)"},
                        {"url":"./tabdd.html#t1r400","alias":"Al-Ustādh (1892)"},
                        {"url":"./tabdd.html#t1r775","alias":"Al-Wakīl (1899)"},
                        {"url":"./tabdd.html#t1r365","alias":"Waqāʾiʿ al-Būlīs (1891)"},
                        {"url":"./tabdd.html#t1r401","alias":"Waqāʾiʿ al-Būlīs (1892)"},
                        {"url":"./tabdd.html#t1r5","alias":"Waqāʾiʿ-i Miṣriyye/Waqāyiʿ Miṣriyya (1828)"},
                        {"url":"./tabdd.html#t1r576","alias":"Al-Waqt (1896)"},
                        {"url":"./tabdd.html#t1r122","alias":"Al-Waṭan (1877)"},
                        {"url":"./tabdd.html#t1r578","alias":"Al-Waẓīfa (1896)"},
                        {"url":"./tabdd.html#t1r49","alias":"Wādī al-Nīl (1867)"},
                        {"url":"./tabdd.html#t1r774","alias":"Al-Wājibāt (1899)"},
                        {"url":"./tabdd.html#t1r715","alias":"Al-Wāsiṭa (1898)"},
                        {"url":"./tabdd.html#t1r37","alias":"Yaʿsūb al-Ṭibb (1865)"},
                        {"url":"./tabdd.html#t1r477","alias":"Al-Yānaṣīb (1894)"},
                        {"url":"./tabdd.html#t1r716","alias":"Yıldız/ Yildīz (1898)"},
                        {"url":"./tabdd.html#t1r717","alias":"Al-Zaman (1898)"},
                        {"url":"./tabdd.html#t1r216","alias":"Al-Zamān (1882)"},
                        {"url":"./tabdd.html#t1r243","alias":"Al-Zamān (1884)"},
                        {"url":"./tabdd.html#t1r366","alias":"Al-Zirāʿa (1891)"},
                        {"url":"./tabdd.html#t1r525","alias":"Al-Zirāʿa al-Miṣriyya (1895)"},
                        {"url":"./tabdd.html#t1r524","alias":"Al-Ẓarāʾif (1895)"},
                        {"url":"./tabdd.html#t1r523","alias":"Al-Ẓāhir (1895)"},
                        {"url":"./tabdd.html#t1r842","alias":"(Al-)Usbūʿ (1900)"}]},
                {
            "label":"Calcutta",
            "type":"city",
            "latlng":"22.56972, 88.36972",
            "periodicals":"5",
            "links":
            [ {"url":"./tabdd.html#t1r87","alias":"Ha-Mevaser/The Jewish Gazette (1873)"},
                        {"url":"./tabdd.html#t1r324","alias":"Maggīd Meshahrim (1889)"},
                        {"url":"./tabdd.html#t1r190","alias":"Mufarriḥ al-Qulūb (c1881)"},
                        {"url":"./tabdd.html#t1r388","alias":"Nukhbat al-Akhbār (1892)"},
                        {"url":"./tabdd.html#t1r132","alias":"Pearah/Pīrah al-Yahūdiyya/The Jewish Gazette (1878)"}]},
                {
            "label":"Campinas",
            "type":"city",
            "latlng":"-22.90556, -47.06083",
            "periodicals":"1",
            "links":
            [ {"url":"./tabdd.html#t1r444","alias":"Al-Fayḥāʾ (1894)"}]},
                {
            "label":"Constantine, Algeria",
            "type":"town",
            "latlng":"36.35, 6.6",
            "periodicals":"3",
            "links":
            [ {"url":"./tabdd.html#t1r664","alias":"Al-Jazāʾir al-Faransiyya al-ʿArabiyya / L’Algérie Franco-Arabe (1898)"},
                        {"url":"./tabdd.html#t1r225","alias":"Al-Mubaṣṣir/El-Mobasser (1883)"},
                        {"url":"./tabdd.html#t1r211","alias":"Al-Muntakhab/ El-Montakheb (1882)"}]},
                {
            "label":"Damascus",
            "type":"city",
            "latlng":"33.5102, 36.29128",
            "periodicals":"7",
            "links":
            [ {"url":"./tabdd.html#t1r128","alias":"Dimashq (1878)"},
                        {"url":"./tabdd.html#t1r264","alias":"Mirʾāt al-Akhlāq (1886)"},
                        {"url":"./tabdd.html#t1r345","alias":"Rawḍat al-Shām (1890)"},
                        {"url":"./tabdd.html#t1r346","alias":"Rūḥān al-Shām (1890?)"},
                        {"url":"./tabdd.html#t1r837","alias":"Al-Shams (1900)"},
                        {"url":"./tabdd.html#t1r567","alias":"Al-Shām (1896)"},
                        {"url":"./tabdd.html#t1r36","alias":"Sūriyya (1865)"}]},
                {
            "label":"Darʿun",
            "type":"town",
            "latlng":"33.984198, 35.662867",
            "periodicals":"2",
            "links":
            [ {"url":"./tabdd.html#t1r378","alias":"Al-Jaʿba (1892)"},
                        {"url":"./tabdd.html#t1r84","alias":"Al-Juʿba (1873)"}]},
                {
            "label":"Dayr al-Qamar",
            "type":"city",
            "latlng":"33.69778, 35.56361",
            "periodicals":"1",
            "links":
            [ {"url":"./tabdd.html#t1r47","alias":"Lubnān (1867)"}]},
                {
            "label":"Delhi",
            "type":"city",
            "latlng":"28.63576, 77.22445",
            "periodicals":"1",
            "links":
            [ {"url":"./tabdd.html#t1r172","alias":"Naṣrat al-Akhbār (1880)"}]},
                {
            "label":"Egypt",
            "type":"country",
            "latlng":"27, 30",
            "periodicals":"10",
            "links":
            [ {"url":"./tabdd.html#t2r853","alias":"Majallat al-ʿArūs (?)"},
                        {"url":"./tabdd.html#t1r459","alias":"Mimfīs (c1894?)"},
                        {"url":"./tabdd.html#t1r344","alias":"Nahḍat Isrāʾīl (1890)"},
                        {"url":"./tabdd.html#t1r820","alias":"Nūr al-Islām (1900)"},
                        {"url":"./tabdd.html#t1r821","alias":"Al-Qalyūbiyya (1900)"},
                        {"url":"./tabdd.html#t1r831","alias":"Al-Salwa (1900)"},
                        {"url":"./tabdd.html#t1r838","alias":"Al-Sharqiyya (1900)"},
                        {"url":"./tabdd.html#t1r827","alias":"Al-Ṣabāʾ (1900)"},
                        {"url":"./tabdd.html#t1r829","alias":"Al-Ṣabwa (1900)"},
                        {"url":"./tabdd.html#t1r200","alias":"Tawfīq (1881)"}]},
                {
            "label":"Fayyūm",
            "type":"city",
            "latlng":"29.30995, 30.8418",
            "periodicals":"2",
            "links":
            [ {"url":"./tabdd.html#t1r445","alias":"Al-Fayyūm (1894)"},
                        {"url":"./tabdd.html#t1r536","alias":"Al-Fayyūm (1896)"}]},
                {
            "label":"Ghawānābārā",
            "type":"town",
            "latlng":"-22.904118, -43.177138",
            "periodicals":"1",
            "links":
            [ {"url":"./tabdd.html#t1r836","alias":"Al-Shaʿb (1900)"}]},
                {
            "label":"Helwan",
            "type":"city",
            "latlng":"29.84144, 31.30084",
            "periodicals":"1",
            "links":
            [ {"url":"./tabdd.html#t1r540","alias":"Al-Ḥimāya (1896)"}]},
                {
            "label":"Ḥaydarābād",
            "type":"city",
            "latlng":"24.92194, 88.79142",
            "periodicals":"1",
            "links":
            [ {"url":"./tabdd.html#t1r322","alias":"Al-Ḥaqāʾiq (1889)"}]},
                {
            "label":"Istanbul",
            "type":"city",
            "latlng":"41.01384, 28.94966",
            "periodicals":"24",
            "links":
            [ {"url":"./tabdd.html#t1r406","alias":"Al-Bayān (1893)"},
                        {"url":"./tabdd.html#t2r851","alias":"Al-Hidāya (?)"},
                        {"url":"./tabdd.html#t1r250","alias":"Al-Ḥaqāʾiq (1885)"},
                        {"url":"./tabdd.html#t1r295","alias":"Al-Ḥaqāʾiq (1888)"},
                        {"url":"./tabdd.html#t1r339","alias":"Al-Ḥuqūq (1890)"},
                        {"url":"./tabdd.html#t1r221","alias":"Al-Iʿtidāl (1883)"},
                        {"url":"./tabdd.html#t1r163","alias":"Al-Insān (1880)"},
                        {"url":"./tabdd.html#t1r232","alias":"Al-Insān (1884)"},
                        {"url":"./tabdd.html#t1r25","alias":"Al-Jawāʾib (1860)"},
                        {"url":"./tabdd.html#t1r233","alias":"Kawkab al-ʿIlm (1884)"},
                        {"url":"./tabdd.html#t1r666","alias":"Kevkeb-i Osmānī / al-Kawkab al-ʿUthmānī (1898)"},
                        {"url":"./tabdd.html#t1r611","alias":"Al-Maʿlūmāt (1897)"},
                        {"url":"./tabdd.html#t1r499","alias":"Al-Maʿlūmāt (ʿArabiyya) (1897)"},
                        {"url":"./tabdd.html#t1r209","alias":"Madrasat al-Funūn/Medrese-i Fünun (1882)"},
                        {"url":"./tabdd.html#t2r852","alias":"Majlis al-Mabʿūthīn (?)"},
                        {"url":"./tabdd.html#t1r550","alias":"Manẓara (1896)"},
                        {"url":"./tabdd.html#t1r16","alias":"Mirʾāt al-Aḥwāl (1855)"},
                        {"url":"./tabdd.html#t1r154","alias":"Al-Salām (1879)"},
                        {"url":"./tabdd.html#t1r257","alias":"Al-Salām (1885)"},
                        {"url":"./tabdd.html#t1r18","alias":"Al-Salṭana (1857)"},
                        {"url":"./tabdd.html#t1r628","alias":"Al-Salṭana (1897)"},
                        {"url":"./tabdd.html#t1r844","alias":"Al-Shām: Muḥāḍarāt wa Muqtaṭafāt (1883)"},
                        {"url":"./tabdd.html#t1r768","alias":"Siyāḥatī/Seyahati; resimli devr-i âlem (1899)"},
                        {"url":"./tabdd.html#t1r287","alias":"Sūq al-ʿUkāz / Sūq-i ʿUkāz (1887)"}]},
                {
            "label":"Jerusalem",
            "type":"city",
            "latlng":"31.78336, 35.23388",
            "periodicals":"1",
            "links":
            [ {"url":"./tabdd.html#t1r102","alias":"Al-Ghazzāl (1876)"}]},
                {
            "label":"Jounieh / Jūnī (Lebanon)",
            "type":"town",
            "latlng":"33.9877, 35.638924",
            "periodicals":"2",
            "links":
            [ {"url":"./tabdd.html#t1r484","alias":"Al-Arz (1895)"},
                        {"url":"./tabdd.html#t1r824","alias":"Al-Raʾīs (1900)"}]},
                {
            "label":"Kafr Matā",
            "type":"",
            "latlng":", ",
            "periodicals":"1",
            "links":
            [ {"url":"./tabdd.html#t1r270","alias":"Al-Ṣafāʾ (1886)"}]},
                {
            "label":"Khartoum",
            "type":"city",
            "latlng":"15.55177, 32.53241",
            "periodicals":"1",
            "links":
            [ {"url":"./tabdd.html#t1r730","alias":"Al-Ghāzītiyya al-Sūdāniyya (1899)"}]},
                {
            "label":"Kiftīn (Lebanon)",
            "type":"",
            "latlng":", ",
            "periodicals":"1",
            "links":
            [ {"url":"./tabdd.html#t1r223","alias":"Lubān al-Albāb (1883)"}]},
                {
            "label":"Lahore",
            "type":"city",
            "latlng":"31.54972, 74.34361",
            "periodicals":"1",
            "links":
            [ {"url":"./tabdd.html#t1r72","alias":"Al-Nafʿ al-ʿAzīm li-Ahl hadha ’l-Iqlīm (1871)"}]},
                {
            "label":"Lattakia",
            "type":"city",
            "latlng":"35.51484, 35.77684",
            "periodicals":"2",
            "links":
            [ {"url":"./tabdd.html#t1r677","alias":"Al-Manār (1898)"},
                        {"url":"./tabdd.html#t1r677","alias":"Al-Manār (1898)"}]},
                {
            "label":"Lebanon",
            "type":"country",
            "latlng":"33.83333, 35.83333",
            "periodicals":"7",
            "links":
            [ {"url":"./tabdd.html#t1r378","alias":"Al-Jaʿba (1892)"},
                        {"url":"./tabdd.html#t1r84","alias":"Al-Juʿba (1873)"},
                        {"url":"./tabdd.html#t1r47","alias":"Lubnān (1867)"},
                        {"url":"./tabdd.html#t1r359","alias":"Lubnān (1891)"},
                        {"url":"./tabdd.html#t1r468","alias":"Al-Rawḍa (1894)"},
                        {"url":"./tabdd.html#t1r699","alias":"Al-Saʿāda (1898)"},
                        {"url":"./tabdd.html#t1r433","alias":"Ṭarābulus / then Ṭarābulus al-Shām (1893)"}]},
                {
            "label":"Libya",
            "type":"country",
            "latlng":"28, 17",
            "periodicals":"2",
            "links":
            [ {"url":"./tabdd.html#t1r632","alias":"Al-Taraqqī (1897)"},
                        {"url":"./tabdd.html#t1r41","alias":"Ṭarābulus al-Gharb (1866)"}]},
                {
            "label":"Livorno",
            "type":"city",
            "latlng":"43.54264, 10.316",
            "periodicals":"4",
            "links":
            [ {"url":"./tabdd.html#t1r124","alias":"Al-ʿAmāla al-Tūnisiyya/La Province Tunisienne (1878)"},
                        {"url":"./tabdd.html#t1r160","alias":"Al-Anbāʾ (1880)"},
                        {"url":"./tabdd.html#t1r218","alias":"Al-Anbāʾ (1883)"},
                        {"url":"./tabdd.html#t1r236","alias":"Al-Mubashshir (1884)"}]},
                {
            "label":"London",
            "type":"city",
            "latlng":"51.50853, -0.12574",
            "periodicals":"15",
            "links":
            [ {"url":"./tabdd.html#t1r78","alias":"Āl Sām (1872)"},
                        {"url":"./tabdd.html#t1r370","alias":"Ḍiyāʾ al-Khāfiqayn (1892)"},
                        {"url":"./tabdd.html#t1r183","alias":"Al-Ghayra (1881)"},
                        {"url":"./tabdd.html#t1r142","alias":"Ḥall al-Masʾalatayn al-Sharqiyya wa’l-Gharbiyya (1879)"},
                        {"url":"./tabdd.html#t1r186","alias":"Al-Ittiḥād al-ʿArabī (1881)"},
                        {"url":"./tabdd.html#t1r188","alias":"Al-Khilāfa (1881)"},
                        {"url":"./tabdd.html#t1r747","alias":"Al-Khilāfa (1899)"},
                        {"url":"./tabdd.html#t1r341","alias":"Kulliyyāt Malkam (1890)"},
                        {"url":"./tabdd.html#t1r16","alias":"Mirʾāt al-Aḥwāl (1855)"},
                        {"url":"./tabdd.html#t1r103","alias":"Mirʾāt al-Aḥwāl fi’l-Siyāsa wa’l-Akhlāq (1876)"},
                        {"url":"./tabdd.html#t1r237","alias":"Al-Naḥla (1884)"},
                        {"url":"./tabdd.html#t1r74","alias":"Al-Naḥla al-Ḥurra (1871)"},
                        {"url":"./tabdd.html#t1r116","alias":"Al-Naḥla/The Bee (1877)"},
                        {"url":"./tabdd.html#t1r466","alias":"Rajʿ al-Ṣadā (1894)"},
                        {"url":"./tabdd.html#t1r53","alias":"Rujūm wa-Ghassāq ilā Fāris al-Shidyāq (1868)"}]},
                {
            "label":"Lucknow",
            "type":"city",
            "latlng":"26.85, 80.91667",
            "periodicals":"1",
            "links":
            [ {"url":"./tabdd.html#t1r826","alias":"Al-Riyāḍ (1900)"}]},
                {
            "label":"Al-Manṣūra",
            "type":"city",
            "latlng":"31.03637, 31.38069",
            "periodicals":"1",
            "links":
            [ {"url":"./tabdd.html#t1r549","alias":"Al-Manṣūra (1896)"}]},
                {
            "label":"Marseille",
            "type":"city",
            "latlng":"43.296482, 5.369780",
            "periodicals":"2",
            "links":
            [ {"url":"./tabdd.html#t1r23","alias":"ʿUṭārid (1858)"},
                        {"url":"./tabdd.html#t1r615","alias":"Al-Mirsāḍ (1897)"}]},
                {
            "label":"Minya",
            "type":"city",
            "latlng":"28.10988, 30.7503",
            "periodicals":"1",
            "links":
            [ {"url":"./tabdd.html#t1r799","alias":"Al-Indhār (1900)"}]},
                {
            "label":"Mosul",
            "type":"city",
            "latlng":"36.335, 43.11889",
            "periodicals":"1",
            "links":
            [ {"url":"./tabdd.html#t1r97","alias":"Al-Mawṣil (Musul) (1875)"}]},
                {
            "label":"Naples",
            "type":"city",
            "latlng":"40.83333, 14.25",
            "periodicals":"2",
            "links":
            [ {"url":"./tabdd.html#t1r143","alias":"Istiqbāl (1879)"},
                        {"url":"./tabdd.html#t1r148","alias":"Al-Khilāfa (1879)"}]},
                {
            "label":"New York",
            "type":"city",
            "latlng":"40.71427, -74.00597",
            "periodicals":"14",
            "links":
            [ {"url":"./tabdd.html#t1r442","alias":"Al-ʿAṣr (1894)"},
                        {"url":"./tabdd.html#t1r641","alias":"Al-ʿĀlam (1898)"},
                        {"url":"./tabdd.html#t1r588","alias":"Al-Ayyām (1897)"},
                        {"url":"./tabdd.html#t1r646","alias":"Al-Ayyām (1898)"},
                        {"url":"./tabdd.html#t1r725","alias":"Al-Ayyām (1899)"},
                        {"url":"./tabdd.html#t1r791","alias":"Al-Dāʾira (1900)"},
                        {"url":"./tabdd.html#t1r660","alias":"Al-Hudā (1898)"},
                        {"url":"./tabdd.html#t1r662","alias":"Al-Iṣlāḥ (1898)"},
                        {"url":"./tabdd.html#t1r739","alias":"Al-Iṣlāḥ (1899)"},
                        {"url":"./tabdd.html#t1r379","alias":"Kawkab Amīrkā (1892)"},
                        {"url":"./tabdd.html#t1r754","alias":"Mirʾāt al-Gharb (1899)"},
                        {"url":"./tabdd.html#t1r757","alias":"Al-Mushīr (1899)"},
                        {"url":"./tabdd.html#t1r463","alias":"Al-Mushīr/ The Counsellor (1894)"},
                        {"url":"./tabdd.html#t1r394","alias":"Al-Rāwī (1892)"}]},
                {
            "label":"Nicosia, Cyprus",
            "type":"city",
            "latlng":"35.166667, 33.366667",
            "periodicals":"5",
            "links":
            [ {"url":"./tabdd.html#t1r593","alias":"Al-Burhān (1897)"},
                        {"url":"./tabdd.html#t1r316","alias":"Dīk al-Sharq (c1889)"},
                        {"url":"./tabdd.html#t1r145","alias":"Juhaynat al-Akhbār (1879)"},
                        {"url":"./tabdd.html#t1r676","alias":"Majmūʿat Qibrīs (1898)"},
                        {"url":"./tabdd.html#t1r138","alias":"Zamān (1878)"}]},
                {
            "label":"Oran",
            "type":"city",
            "latlng":"35.69111, -0.64167",
            "periodicals":"5",
            "links":
            [ {"url":"./tabdd.html#t1r340","alias":"La Jeunesse Israélite (1890)"},
                        {"url":"./tabdd.html#t1r273","alias":"La Vigie Israëlite (1886)"},
                        {"url":"./tabdd.html#t1r274","alias":"L-Wahrani / L’Oranais (1886)"},
                        {"url":"./tabdd.html#t1r333","alias":"Qôl Yisráel / La Voix d’Israël (1889)"},
                        {"url":"./tabdd.html#t1r336","alias":"Tôv-le-Yisra’el (1889)"}]},
                {
            "label":"Paris",
            "type":"city",
            "latlng":"48.85341, 2.3488",
            "periodicals":"45",
            "links":
            [ {"url":"./tabdd.html#t1r242","alias":"Al-ʿUrwa al-Wuthqā (1884)"},
                        {"url":"./tabdd.html#t1r23","alias":"ʿUṭārid (1858)"},
                        {"url":"./tabdd.html#t1r245","alias":"Abou Naddara/Abū Naẓẓāra Zarqā (1885)"},
                        {"url":"./tabdd.html#t1r202","alias":"Abou-Naddara Zarka (1882)"},
                        {"url":"./tabdd.html#t1r176","alias":"Abou-Naddara/Abū Naẓẓāra/ L’Abou Naddara (1881)"},
                        {"url":"./tabdd.html#t1r157","alias":"Abu’l-Ḥawl (1880)"},
                        {"url":"./tabdd.html#t1r140","alias":"Abū Naẓẓāra Zarqā (1879)"},
                        {"url":"./tabdd.html#t1r230","alias":"Abū Naẓẓāra/Abou Naddara (1884)"},
                        {"url":"./tabdd.html#t1r158","alias":"Abū Ṣaffāra / Le Flutiste (1880)"},
                        {"url":"./tabdd.html#t1r159","alias":"Abū Zammāra / La Clarinette (1880)"},
                        {"url":"./tabdd.html#t1r160","alias":"Al-Anbāʾ (1880)"},
                        {"url":"./tabdd.html#t1r218","alias":"Al-Anbāʾ (1883)"},
                        {"url":"./tabdd.html#t1r179","alias":"Al-Baṣīr / Al-Bassir (1881)"},
                        {"url":"./tabdd.html#t1r20","alias":"Birjīs Bārīs (1859)"},
                        {"url":"./tabdd.html#t1r184","alias":"Al-Ḥāwī/Le Charmeur (pseudonym for Abū Naẓẓāra Zarqā) (1881)"},
                        {"url":"./tabdd.html#t1r162","alias":"Al-Ḥuqūq (1880)"},
                        {"url":"./tabdd.html#t1r164","alias":"Al-Ittiḥād/L’Union (1880)"},
                        {"url":"./tabdd.html#t1r357","alias":"Jarīdat Abī Naẓẓāra/Le Journal d’Abou Naddara (1891)"},
                        {"url":"./tabdd.html#t1r452","alias":"Kashf al-Niqāb (1894)"},
                        {"url":"./tabdd.html#t1r208","alias":"Kawkab al-Mashriq/L’Astre d’Orient (1882)"},
                        {"url":"./tabdd.html#t1r222","alias":"Kawkab al-Sharq (1883)"},
                        {"url":"./tabdd.html#t1r850","alias":"L’Aigle de Paris (Birgys) (1860)"},
                        {"url":"./tabdd.html#t1r152","alias":"Miṣr al-Qāhira (1879)"},
                        {"url":"./tabdd.html#t1r327","alias":"Miṣr li-l-Miṣriyyīn (1889)"},
                        {"url":"./tabdd.html#t1r193","alias":"Al-Munṣif (1881)"},
                        {"url":"./tabdd.html#t1r756","alias":"Al-Munṣif /L’Almonsef (L’Équitable) d’Abou Naddara (1899)"},
                        {"url":"./tabdd.html#t1r420","alias":"Al-Murṣid (1893)"},
                        {"url":"./tabdd.html#t1r557","alias":"Al-Murṣid (1896)"},
                        {"url":"./tabdd.html#t1r48","alias":"Al-Mushtarī (1867)"},
                        {"url":"./tabdd.html#t1r212","alias":"Najm al-Mashriq/L’Astre d’Orient (1882)"},
                        {"url":"./tabdd.html#t1r153","alias":"Al-Naẓẓārāt al-Miṣriyya/Ennadarat el-Masriya (1879)"},
                        {"url":"./tabdd.html#t1r173","alias":"Al-Rajāʾ (1880)"},
                        {"url":"./tabdd.html#t1r467","alias":"Al-Rajāʾ (1894)"},
                        {"url":"./tabdd.html#t1r511","alias":"Al-Rajāʾ (1895)"},
                        {"url":"./tabdd.html#t1r133","alias":"Riḥlat Abī Naẓẓāra Zarqā (1878)"},
                        {"url":"./tabdd.html#t1r238","alias":"Al-Shams (1884)"},
                        {"url":"./tabdd.html#t1r258","alias":"Al-Shams/El-Chams/Le Soleil (1885)"},
                        {"url":"./tabdd.html#t1r174","alias":"Al-Sharq (1880)"},
                        {"url":"./tabdd.html#t1r119","alias":"Al-Ṣadā (1877)"},
                        {"url":"./tabdd.html#t1r364","alias":"Ṣadā al-Sharq (1891)"},
                        {"url":"./tabdd.html#t1r199","alias":"Al-Tawaddud (1881)"},
                        {"url":"./tabdd.html#t1r398","alias":"Al-Tawaddud (1892)"},
                        {"url":"./tabdd.html#t1r773","alias":"Al-Tawaddud / L’Attawadad d’Abou Naddara (1899)"},
                        {"url":"./tabdd.html#t1r522","alias":"Turkiyā al-Fatāt/La Jeune Turquie (1895)"},
                        {"url":"./tabdd.html#t1r228","alias":"Al-Waṭanī al-Miṣrī/The Egyptian Patriot (1883)"}]},
                {
            "label":"Philadelphia",
            "type":"city",
            "latlng":"39.952335, -75.163789",
            "periodicals":"4",
            "links":
            [ {"url":"./tabdd.html#t1r442","alias":"Al-ʿAṣr (1894)"},
                        {"url":"./tabdd.html#t2r846","alias":"Al-ʿAṣr (?)"},
                        {"url":"./tabdd.html#t1r660","alias":"Al-Hudā (1898)"},
                        {"url":"./tabdd.html#t1r776","alias":"Al-Waṭaniyya (1899)"}]},
                {
            "label":"Port Said",
            "type":"city",
            "latlng":"31.25654, 32.28412",
            "periodicals":"1",
            "links":
            [ {"url":"./tabdd.html#t1r127","alias":"Al-Būsfūr / Le Bosphore égyptien (1878)"}]},
                {
            "label":"Punjab",
            "type":"region",
            "latlng":"30.86017, 72.31976",
            "periodicals":"1",
            "links":
            [ {"url":"./tabdd.html#t1r170","alias":"Al-Nafʿ al-ʿAzīm (1880)"}]},
                {
            "label":"Rio de Janeiro",
            "type":"city",
            "latlng":"-22.90278, -43.2075",
            "periodicals":"3",
            "links":
            [ {"url":"./tabdd.html#t1r781","alias":"Al-ʿAdl (1900)"},
                        {"url":"./tabdd.html#t1r565","alias":"Al-Raqīb (1896)"},
                        {"url":"./tabdd.html#t1r834","alias":"Al-Ṣawāb (1900)"}]},
                {
            "label":"Saint Lawrence",
            "type":"city",
            "latlng":"-39.88333, 176.76667",
            "periodicals":"1",
            "links":
            [ {"url":"./tabdd.html#t2r850","alias":"Al-Iqbāl (?)"}]},
                {
            "label":"Sanaa",
            "type":"city",
            "latlng":"15.35472, 44.20667",
            "periodicals":"2",
            "links":
            [ {"url":"./tabdd.html#t1r155","alias":"Ṣanʿāʾ (1879)"},
                        {"url":"./tabdd.html#t1r81","alias":"Al-Yaman (1872)"}]},
                {
            "label":"Sao Paulo",
            "type":"city",
            "latlng":"-23.5475, -46.63611",
            "periodicals":"6",
            "links":
            [ {"url":"./tabdd.html#t1r645","alias":"Al-Aṣmaʿī (1898)"},
                        {"url":"./tabdd.html#t1r648","alias":"Al-Barāzil (1898)"},
                        {"url":"./tabdd.html#t1r444","alias":"Al-Fayḥāʾ (1894)"},
                        {"url":"./tabdd.html#t1r753","alias":"Al-Manāẓir (1899)"},
                        {"url":"./tabdd.html#t1r815","alias":"Al-Minshar (1900)"},
                        {"url":"./tabdd.html#t1r616","alias":"Al-Munāẓir (1897)"}]},
                {
            "label":"Shibīn al-Kawm (Shibin el-Kom)",
            "type":"town",
            "latlng":"30.56667, 30.96667",
            "periodicals":"2",
            "links":
            [ {"url":"./tabdd.html#t1r759","alias":"Al-Mustashār (1899?)"},
                        {"url":"./tabdd.html#t1r762","alias":"Rawḍat al-Baḥrayn (1899)"}]},
                {
            "label":"Shiraz",
            "type":"city",
            "latlng":"29.61031, 52.53114",
            "periodicals":"1",
            "links":
            [ {"url":"./tabdd.html#t1r79","alias":"Fars (1872)"}]},
                {
            "label":"Suez",
            "type":"city",
            "latlng":"29.97371, 32.52627",
            "periodicals":"1",
            "links":
            [ {"url":"./tabdd.html#t1r733","alias":"Al-Ḥayāt (1899)"}]},
                {
            "label":"Syria",
            "type":"country",
            "latlng":"35, 38",
            "periodicals":"1",
            "links":
            [ {"url":"./tabdd.html#t1r433","alias":"Ṭarābulus / then Ṭarābulus al-Shām (1893)"}]},
                {
            "label":"Tangier",
            "type":"city",
            "latlng":"35.76727, -5.79975",
            "periodicals":"2",
            "links":
            [ {"url":"./tabdd.html#t1r325","alias":"Al-Maghrib (1889)"},
                        {"url":"./tabdd.html#t1r749","alias":"Al-Maghrib (1899)"}]},
                {
            "label":"Tanta",
            "type":"city",
            "latlng":"30.78847, 31.00192",
            "periodicals":"2",
            "links":
            [ {"url":"./tabdd.html#t1r755","alias":"Al-Mumtāz (1899)"},
                        {"url":"./tabdd.html#t1r571","alias":"Ṭanṭā (1896)"}]},
                {
            "label":"Tripoli",
            "type":"city",
            "latlng":"32.87519, 13.18746",
            "periodicals":"4",
            "links":
            [ {"url":"./tabdd.html#t1r632","alias":"Al-Taraqqī (1897)"},
                        {"url":"./tabdd.html#t1r41","alias":"Ṭarābulus al-Gharb (1866)"},
                        {"url":"./tabdd.html#t1r397","alias":"Ṭarābulus al-Shām (1892)"},
                        {"url":"./tabdd.html#t1r433","alias":"Ṭarābulus / then Ṭarābulus al-Shām (1893)"}]},
                {
            "label":"Tunis",
            "type":"city",
            "latlng":"36.81897, 10.16579",
            "periodicals":"41",
            "links":
            [ {"url":"./tabdd.html#t1r261","alias":"Al-Badr al-Kāmil (1886)"},
                        {"url":"./tabdd.html#t1r405","alias":"Al-Baṣīra/Le Clairevoyant (1893)"},
                        {"url":"./tabdd.html#t1r291","alias":"Al-Bustān/El Boustan/Le Jardin (1888)"},
                        {"url":"./tabdd.html#t1r280","alias":"Fāḍiḥ al-Asrār (1887)"},
                        {"url":"./tabdd.html#t1r320","alias":"Ḥanaṣnīm (1889)"},
                        {"url":"./tabdd.html#t1r490","alias":"Al-Ḥaqīqa (1895)"},
                        {"url":"./tabdd.html#t1r294","alias":"Al-Ḥāḍira (1888)"},
                        {"url":"./tabdd.html#t1r296","alias":"Al-Ḥurriyya/La Liberté (1888)"},
                        {"url":"./tabdd.html#t1r411","alias":"Al-Ittiḥād al-Isrāʾīlī/L’Union Israélite (1893)"},
                        {"url":"./tabdd.html#t1r281","alias":"Al-Jinān/Habārdīs/Happardis (1887)"},
                        {"url":"./tabdd.html#t1r298","alias":"Jurnāl Hajīn/Le Journal de la fête du grand dieul (1888)"},
                        {"url":"./tabdd.html#t1r413","alias":"Khaznat al-Gharām (1893)"},
                        {"url":"./tabdd.html#t1r609","alias":"Kitāb Riyāqāt al-Nufūs (1897)"},
                        {"url":"./tabdd.html#t1r849","alias":"Le Réveil (1889)"},
                        {"url":"./tabdd.html#t1r547","alias":"Lisān al-Ḥaqq/Liçan El-Hak (1896)"},
                        {"url":"./tabdd.html#t1r302","alias":"Al-Marisṭān (1888)"},
                        {"url":"./tabdd.html#t1r236","alias":"Al-Mubashshir (1884)"},
                        {"url":"./tabdd.html#t1r253","alias":"Al-Mubashshir al-Ṣādiq/Le Messager intègre (1885)"},
                        {"url":"./tabdd.html#t1r343","alias":"Al-Mubashshir al-Tūnisī (1890)"},
                        {"url":"./tabdd.html#t1r382","alias":"Al-Mubashshir al-Tūnisī/Le Messager Tunisien (1892)"},
                        {"url":"./tabdd.html#t1r362","alias":"Al-Muḥayyir/El-Mouhayer (1891)"},
                        {"url":"./tabdd.html#t1r265","alias":"Munawwir al-Ḥaqq (1886)"},
                        {"url":"./tabdd.html#t1r195","alias":"Muntakhabāt al-Rāʾid al-Tūnisī al-Rasmiyya (1881)"},
                        {"url":"./tabdd.html#t1r383","alias":"Al-Muntaẓar/Le Messie (1892)"},
                        {"url":"./tabdd.html#t1r266","alias":"Mushriḥ al-Aṣdār/Machrecho Lasdar (1886)"},
                        {"url":"./tabdd.html#t1r284","alias":"Al-Mutarjim/L’Interprète (1887)"},
                        {"url":"./tabdd.html#t1r384","alias":"Al-Naḥla al-Usbūʿiyya (1892)"},
                        {"url":"./tabdd.html#t1r303","alias":"Al-Najma/L’Étoile (1888)"},
                        {"url":"./tabdd.html#t1r33","alias":"Natāʾij al-Akhbār (1863)"},
                        {"url":"./tabdd.html#t1r304","alias":"Natāʾij al-Akhbār (1888)"},
                        {"url":"./tabdd.html#t1r387","alias":"Nāṣir al-Muḥayyirīn (1892)"},
                        {"url":"./tabdd.html#t1r360","alias":"Al-Nuṣra/El-Nosra/La Victoire (1891)"},
                        {"url":"./tabdd.html#t1r92","alias":"Al-Nuzha al-Khayriyya (1874)"},
                        {"url":"./tabdd.html#t1r307","alias":"Al-Qaṣbāʾ (1888)"},
                        {"url":"./tabdd.html#t1r27","alias":"Al-Rāʾid al-Tūnisī (1860)"},
                        {"url":"./tabdd.html#t1r512","alias":"Sabīl al-Rashād (1895)"},
                        {"url":"./tabdd.html#t1r238","alias":"Al-Shams (1884)"},
                        {"url":"./tabdd.html#t1r258","alias":"Al-Shams/El-Chams/Le Soleil (1885)"},
                        {"url":"./tabdd.html#t1r335","alias":"Al-Tilighrāf (1889)"},
                        {"url":"./tabdd.html#t1r399","alias":"Al-Tūnisī/Le Tunisien (1892)"},
                        {"url":"./tabdd.html#t1r348","alias":"Al-Zuhra (1890)"}]},
                {
            "label":"Valetta (Malta)",
            "type":"town",
            "latlng":"35.898397, 14.514686",
            "periodicals":"3",
            "links":
            [ {"url":"./tabdd.html#t1r843","alias":"Akhbār al-Qāṣid (1833)"},
                        {"url":"./tabdd.html#t1r29","alias":"Risālat Qalb Yasūʿ al-Mālṭiyya / Il Messaggier (1861)"},
                        {"url":"./tabdd.html#t1r326","alias":"Mālṭa Taghna (1889)"}]},
                {
            "label":"Wahran, Algeria",
            "type":"",
            "latlng":", ",
            "periodicals":"1",
            "links":
            [ {"url":"./tabdd.html#t1r548","alias":"Maguid Micharim (1896)"}]},
                {
            "label":"Woking",
            "type":"city",
            "latlng":"51.31903, -0.55893",
            "periodicals":"1",
            "links":
            [ {"url":"./tabdd.html#t1r321","alias":"Al-Ḥaqāʾiq/The Arabic Quarterly Review (1889)"}]},
                {
            "label":"Zanzibar",
            "type":"city",
            "latlng":"-6.16394, 39.19793",
            "periodicals":"2",
            "links":
            [ {"url":"./tabdd.html#t1r606","alias":"Jazīt al-Shānba / The Shamba (1897)"},
                        {"url":"./tabdd.html#t1r605","alias":"Al-Jāzit al-Muʾlin bi’l-Bashāʾir wa’l-Asrār (1897)"}]},
                {
            "label":"Zaqaziq",
            "type":"city",
            "latlng":"30.58768, 31.502",
            "periodicals":"5",
            "links":
            [ {"url":"./tabdd.html#t1r820","alias":"Nūr al-Islām (1900)"},
                        {"url":"./tabdd.html#t1r831","alias":"Al-Salwa (1900)"},
                        {"url":"./tabdd.html#t1r838","alias":"Al-Sharqiyya (1900)"},
                        {"url":"./tabdd.html#t1r827","alias":"Al-Ṣabāʾ (1900)"},
                        {"url":"./tabdd.html#t1r829","alias":"Al-Ṣabwa (1900)"}]}],
	"types": {
		"City": {
			"pluralLabel": "Cities"
		}
	},
	"properties": {
		"rank": {
			"valueType": "number"
		},
		"periodicals": {
			"valueType": "number"
		}
	}
}